---
title: "Mode Share"
date: today
---

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import util

pd.set_option('display.float_format', '{:,.1%}'.format)

In [2]:
# add trip type to trip tables
def prep_trip_df(trip):
    """Mode shares will represent shares across Drive Alone, Shared Ride, 
       public transit, and walk and bike trips only. 
    """
    df_trip = trip.copy()
    df_trip.rename(columns={'mode':'Mode'}, inplace=True)
    df_trip['Trip Type'] = 'Non-Work'
    df_trip.loc[df_trip['dpurp'] == 'Work', 'Trip Type'] = 'Work'

    # add all tripa
    df = df_trip.copy()
    df['Trip Type'] = 'All Trips'
    df_trip = pd.concat([df_trip.sort_values('Trip Type'), df], ignore_index=True)

    # Exclude TNC, School Bus, and Other modes
    df_trip = df_trip[~df_trip['Mode'].isin(['TNC', 'School Bus', 'Other'])]

    # Aggregate modes
    df_trip['Mode'] = df_trip['Mode'].replace({
        'SOV': 'Drove Alone',
        'HOV2': 'Shared Ride',
        'HOV3+': 'Shared Ride',
        'Transit': 'Transit',
        'Walk': 'Walk',
        'Bike': 'Bike',
    })

    return df_trip

In [3]:
person = pd.read_csv(util.output_path / 'agg/dash/person_geog.csv')

# counties
trip_county = prep_trip_df(pd.read_csv(util.output_path / 'agg/dash/mode_share_county.csv'))
# remove "Outside Region"
trip_county = trip_county[trip_county['hh_county'] != 'Outside Region']
# regional geographies
trip_rg = prep_trip_df(pd.read_csv(util.output_path / 'agg/dash/mode_share_rg.csv'))
# centers
trip_rgc = pd.read_csv(util.output_path / 'agg/dash/mode_share_rgc.csv')
# add all RGCs
df = trip_rgc[trip_rgc['hh_rgc'] != 'Not in RGC'].groupby(['dpurp','mode']).sum()[['trexpfac']].reset_index()
df['hh_rgc'] = 'All RGCs'
trip_rgc = pd.concat([df, trip_rgc])
trip_rgc = prep_trip_df(trip_rgc)

In [4]:
# equity geographies
equity_geogs = util.summary_config['hh_equity_geogs']
trip_equity_geog = pd.DataFrame()
for geog in equity_geogs:
    df = prep_trip_df(pd.read_csv(util.output_path/ ('agg/dash/mode_share_'+geog+'.csv')))
    df['equity_geog'] = df[geog].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'})
    
    trip_equity_geog = pd.concat([trip_equity_geog, df[['dpurp', 'Mode', 'equity_geog', 'trexpfac', 'Trip Type']]])

## regional mode share

In [5]:
df1 = trip_county.groupby(['Trip Type','Mode'],as_index=False)['trexpfac'].sum()
df2 = trip_county.groupby(['Trip Type'],as_index=False)['trexpfac'].sum()
df2.rename(columns={'trexpfac':'total_trips'}, inplace=True)

df = df1.merge(df2, on='Trip Type')
df['mode_share'] = df['trexpfac'] / df['total_trips']

df.pivot_table(columns='Mode', index='Trip Type', values='mode_share')

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
Trip Type
All Trips  1.7%        42.2%        34.9%     3.7% 17.6%
Non-Work   1.7%        38.4%        37.9%     3.6% 18.4%
Work       1.6%        66.8%        15.0%     4.1% 12.4%

## trip mode share by home location

:::{.panel-tabset}

### County

In [6]:
def calc_mode_share(df_trip, geog):
    
    # num trips by mode
    df1 = df_trip.groupby([geog, 'Trip Type', 'Mode'],as_index=False)['trexpfac'].sum()
    # num trips
    df2 = df_trip.groupby([geog, 'Trip Type'],as_index=False)['trexpfac'].sum()
    df2.rename(columns={'trexpfac':'total_trips'}, inplace=True)

    df = df1.merge(df2, on=[geog, 'Trip Type'])
    # mode share
    df['mode_share'] = df['trexpfac'] / df['total_trips']

    # mode share by trip type
    df_all = df.loc[df['Trip Type']=="All Trips"].pivot_table(columns='Mode', index=geog, values='mode_share')
    df_work = df.loc[df['Trip Type']=="Work"].pivot_table(columns='Mode', index=geog, values='mode_share')
    df_non_work = df.loc[df['Trip Type']=="Non-Work"].pivot_table(columns='Mode', index=geog, values='mode_share')
    # num trips by trip type
    trip_all = df.loc[df['Trip Type']=="All Trips"].pivot_table(columns='Mode', index=geog, values='trexpfac')
    trip_work = df.loc[df['Trip Type']=="Work"].pivot_table(columns='Mode', index=geog, values='trexpfac')
    trip_non_work = df.loc[df['Trip Type']=="Non-Work"].pivot_table(columns='Mode', index=geog, values='trexpfac')

    return df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work


df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work = calc_mode_share(trip_county,'hh_county')

:::{.panel-tabset}

#### All Purposes

In [7]:
df_all

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
hh_county
King       1.9%        40.0%        32.7%     5.2% 20.2%
Kitsap     1.4%        45.3%        35.6%     1.9% 15.8%
Pierce     1.6%        43.6%        38.1%     1.6% 15.2%
Snohomish  1.4%        45.6%        37.3%     2.0% 13.6%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [8]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [9]:
df_non_work

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
hh_county
King       1.9%        36.3%        35.7%     5.3% 20.9%
Kitsap     1.4%        41.9%        38.4%     1.4% 16.8%
Pierce     1.6%        39.7%        41.1%     1.4% 16.1%
Snohomish  1.5%        41.5%        40.5%     1.9% 14.6%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [10]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [11]:
df_work

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
hh_county
King       1.9%        62.7%        14.4%     5.0% 16.0%
Kitsap     1.1%        69.9%        14.5%     5.7%  8.8%
Pierce     1.4%        71.8%        16.0%     2.5%  8.4%
Snohomish  1.2%        73.2%        16.3%     2.6%  6.7%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [12]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Regional Growth Center

:::{.panel-tabset}

#### All Purposes

In [13]:
df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_rgc, 'hh_rgc')

df_all

Mode                             Bike  Drove Alone  Shared Ride  Transit  Walk
hh_rgc
All RGCs                         3.1%        22.4%        17.1%     7.7% 49.7%
Auburn                           2.5%        30.9%        27.1%     5.4% 34.2%
Bellevue                         3.0%        15.6%        15.0%     7.8% 58.6%
Bothell Canyon Park              1.6%        43.9%        36.0%     1.9% 16.6%
Bremerton                        2.7%        26.1%        20.2%     3.0% 47.9%
Burien                           1.8%        38.1%        27.2%     5.0% 28.0%
Everett                          2.7%        24.9%        19.3%     3.1% 50.0%
Federal Way                      2.1%        31.3%        29.7%     6.9% 30.0%
Greater Downtown Kirkland        2.1%        42.5%        27.0%     5.6% 22.8%
Issaquah                         2.2%        43.4%        22.1%     3.3% 28.9%
Kent                             2.8%        24.9%        24.3%     5.0% 43.0%
Kirkland Totem Lake              2.4%        42.8%        28.6%     3.7% 22.5%
Lakewood                         2.7%        33.6%        24.7%     2.7% 36.3%
Lynnwood                         2.4%        33.4%        27.1%     7.1% 30.0%
Not in RGC                       1.5%        44.8%        37.2%     3.1% 13.4%
Puyallup Downtown                2.4%        36.0%        26.2%     3.0% 32.3%
Puyallup South Hill              1.6%        43.9%        29.0%     1.8% 23.7%
Redmond Downtown                 3.4%        30.7%        23.6%     6.5% 35.8%
Redmond-Overlake                 3.5%        28.2%        23.1%     9.8% 35.4%
Renton                           2.4%        34.3%        26.0%     5.1% 32.1%
SeaTac                           2.3%        36.1%        33.2%     8.4% 20.0%
Seattle Downtown                 3.2%         7.7%         6.8%     7.6% 74.6%
Seattle First Hill/Capitol Hill  3.6%        13.6%         9.5%    11.5% 61.8%
Seattle Northgate                2.8%        30.7%        22.0%    16.7% 27.9%
Seattle South Lake Union         3.7%        13.4%         9.5%     6.7% 66.6%
Seattle University Community     4.6%        23.1%        13.8%    17.9% 40.6%
Seattle Uptown                   4.2%        19.9%        13.1%     7.9% 54.8%
Silverdale                       1.6%        42.2%        19.5%     1.0% 35.7%
Tacoma Downtown                  3.4%        21.2%        17.2%     5.2% 53.0%
Tacoma Mall                      3.0%        32.2%        27.1%     3.4% 34.3%
Tukwila                          2.8%        38.5%        30.3%     5.3% 23.2%
University Place                 2.4%        41.4%        29.7%     2.3% 24.2%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [14]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [15]:
df_non_work

Mode                             Bike  Drove Alone  Shared Ride  Transit  Walk
hh_rgc
All RGCs                         3.1%        19.8%        18.7%     8.0% 50.4%
Auburn                           2.3%        27.6%        28.9%     4.8% 36.5%
Bellevue                         2.9%        13.6%        16.5%     8.2% 58.7%
Bothell Canyon Park              1.7%        40.0%        38.8%     1.8% 17.7%
Bremerton                        2.6%        23.0%        21.6%     2.3% 50.5%
Burien                           1.7%        33.1%        29.0%     5.3% 30.9%
Everett                          2.5%        21.5%        20.6%     3.2% 52.2%
Federal Way                      2.0%        27.3%        31.5%     6.9% 32.3%
Greater Downtown Kirkland        2.0%        38.5%        29.6%     5.4% 24.5%
Issaquah                         2.1%        39.0%        23.9%     3.3% 31.7%
Kent                             2.6%        21.7%        25.9%     4.5% 45.3%
Kirkland Totem Lake              2.3%        38.1%        31.4%     3.8% 24.3%
Lakewood                         2.7%        29.6%        26.4%     2.4% 38.8%
Lynnwood                         2.4%        29.6%        28.9%     6.9% 32.2%
Not in RGC                       1.5%        40.7%        40.4%     3.0% 14.4%
Puyallup Downtown                2.3%        32.2%        27.9%     2.4% 35.2%
Puyallup South Hill              1.5%        39.6%        31.4%     1.5% 25.9%
Redmond Downtown                 3.3%        26.4%        25.6%     6.3% 38.5%
Redmond-Overlake                 3.4%        24.2%        24.8%    10.0% 37.5%
Renton                           2.3%        30.1%        28.1%     5.4% 34.1%
SeaTac                           2.2%        32.2%        35.8%     8.6% 21.1%
Seattle Downtown                 3.4%         6.7%         7.5%     8.6% 73.7%
Seattle First Hill/Capitol Hill  3.6%        11.8%        10.4%    12.3% 61.9%
Seattle Northgate                2.7%        26.8%        23.9%    16.3% 30.2%
Seattle South Lake Union         3.9%        11.9%        10.5%     7.5% 66.2%
Seattle University Community     4.6%        19.2%        14.5%    17.8% 43.9%
Seattle Uptown                   4.0%        17.0%        14.3%     8.6% 56.0%
Silverdale                       1.7%        38.7%        21.1%     0.8% 37.8%
Tacoma Downtown                  3.2%        18.5%        18.4%     5.1% 54.7%
Tacoma Mall                      2.9%        28.2%        28.9%     3.1% 36.8%
Tukwila                          2.7%        33.9%        33.1%     5.2% 25.1%
University Place                 2.4%        37.1%        31.9%     2.3% 26.4%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [16]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [17]:
df_work

Mode                             Bike  Drove Alone  Shared Ride  Transit  Walk
hh_rgc
All RGCs                         3.3%        35.8%         8.7%     6.3% 45.8%
Auburn                           3.4%        54.4%        14.3%    10.1% 17.9%
Bellevue                         3.4%        25.7%         7.5%     5.5% 57.9%
Bothell Canyon Park              1.5%        71.0%        16.8%     2.0%  8.8%
Bremerton                        3.6%        46.3%        10.9%     8.1% 31.2%
Burien                           2.2%        70.2%        15.4%     3.1%  9.1%
Everett                          3.6%        46.2%        11.0%     2.6% 36.7%
Federal Way                      2.7%        60.1%        17.3%     6.4% 13.6%
Greater Downtown Kirkland        2.7%        66.2%        11.9%     6.2% 13.0%
Issaquah                         2.2%        68.4%        12.2%     3.7% 13.5%
Kent                             4.4%        46.3%        13.8%     8.0% 27.5%
Kirkland Totem Lake              2.9%        69.8%        12.4%     2.9% 12.0%
Lakewood                         2.9%        63.5%        11.5%     5.3% 16.8%
Lynnwood                         2.6%        58.9%        14.4%     8.9% 15.3%
Not in RGC                       1.4%        71.7%        16.1%     3.8%  7.1%
Puyallup Downtown                3.7%        62.2%        14.6%     7.3% 12.2%
Puyallup South Hill              1.9%        70.0%        14.4%     3.4% 10.2%
Redmond Downtown                 4.2%        55.1%        12.4%     7.6% 20.7%
Redmond-Overlake                 4.2%        50.9%        13.4%     8.5% 23.0%
Renton                           3.1%        59.7%        13.8%     3.4% 19.9%
SeaTac                           2.6%        62.3%        16.1%     6.5% 12.5%
Seattle Downtown                 2.5%        11.8%         3.8%     3.4% 78.5%
Seattle First Hill/Capitol Hill  3.4%        21.7%         5.6%     7.9% 61.4%
Seattle Northgate                3.1%        53.2%        11.1%    18.7% 14.0%
Seattle South Lake Union         3.0%        20.1%         5.3%     3.3% 68.3%
Seattle University Community     4.4%        44.5%        10.3%    18.8% 22.0%
Seattle Uptown                   4.8%        33.4%         7.8%     4.5% 49.5%
Silverdale                       1.4%        64.6%         9.7%     2.4% 21.9%
Tacoma Downtown                  4.2%        38.1%         9.8%     5.9% 42.0%
Tacoma Mall                      3.6%        61.1%        13.9%     5.8% 15.6%
Tukwila                          3.7%        64.6%        14.1%     5.8% 11.8%
University Place                 2.7%        69.9%        15.0%     2.6%  9.8%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [18]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Regional Geography

:::{.panel-tabset}

#### All Purposes

In [19]:
df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_rg, 'hh_rg_proposed')

df_all

Mode,Bike,Drove Alone,Shared Ride,Transit,Walk
hh_rg_proposed,,,,,
Cities and Towns,1.2%,46.1%,39.3%,1.1%,12.2%
Core Cities,1.6%,43.1%,36.7%,3.4%,15.2%
High Capacity Transit Communities,1.4%,45.3%,37.7%,3.0%,12.5%
Metropolitan Cities,2.4%,34.9%,27.3%,6.3%,29.1%
Rural Areas,0.9%,51.3%,41.0%,0.6%,6.2%
Urban Unincorporated Areas,1.2%,45.4%,43.0%,0.9%,9.5%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [20]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [21]:
df_non_work

Mode,Bike,Drove Alone,Shared Ride,Transit,Walk
hh_rg_proposed,,,,,
Cities and Towns,1.3%,41.9%,42.6%,1.0%,13.2%
Core Cities,1.7%,38.9%,39.8%,3.3%,16.3%
High Capacity Transit Communities,1.5%,41.3%,40.9%,2.8%,13.5%
Metropolitan Cities,2.3%,31.4%,29.9%,6.4%,30.0%
Rural Areas,1.0%,47.6%,44.5%,0.5%,6.4%
Urban Unincorporated Areas,1.3%,41.4%,46.4%,0.8%,10.1%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [22]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [23]:
df_work

Mode,Bike,Drove Alone,Shared Ride,Transit,Walk
hh_rg_proposed,,,,,
Cities and Towns,0.7%,74.9%,17.2%,1.8%,5.3%
Core Cities,1.6%,70.1%,16.2%,4.1%,8.0%
High Capacity Transit Communities,1.2%,72.1%,16.4%,4.2%,6.1%
Metropolitan Cities,2.6%,55.5%,12.5%,5.5%,23.9%
Rural Areas,0.5%,78.1%,15.9%,1.4%,4.1%
Urban Unincorporated Areas,0.8%,76.3%,16.8%,1.7%,4.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [24]:
trip_work.style.format("{:0,.0f}")

:::

:::

In [25]:
equity_geogs = util.summary_config['hh_equity_geogs']

trip_equity_geog = pd.DataFrame()
df_all = pd.DataFrame()
df_work = pd.DataFrame()
df_non_work = pd.DataFrame()
trip_work = pd.DataFrame()
trip_non_work = pd.DataFrame()

for geog in equity_geogs:
    df = prep_trip_df(pd.read_csv(util.output_path/ ('agg/dash/mode_share_'+geog+'.csv')))
    df['equity_geog'] = df[geog].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'})
    df['EFA'] = geog
    # trip_equity_geog = pd.concat([trip_equity_geog, df[['equity_geog_type', 'dpurp', 'Mode', 'equity_geog','trexpfac', 'Trip Type']]])

    _df_all, _df_work, _df_non_work, _trip_all, _trip_work, _trip_non_work = calc_mode_share(df, 'equity_geog')

    _df_all['EFA'] = geog
    _df_work['EFA'] = geog
    _df_non_work['EFA'] = geog
    _trip_all['EFA'] = geog
    _trip_work['EFA'] = geog
    _trip_non_work['EFA'] = geog


    df_all = pd.concat([df_all, _df_all])
    df_work = pd.concat([df_work, _df_work])
    df_non_work = pd.concat([df_non_work, _df_non_work])
    trip_all = pd.concat([trip_all, _trip_all])
    trip_work = pd.concat([trip_work, _trip_work])
    trip_non_work = pd.concat([trip_non_work, _trip_non_work])

col_dict = {'hh_efa_dis': 'Disability',
                                'hh_efa_pov200': 'Income',
                                'hh_efa_poc': 'People of Color',
                                'hh_efa_lep': 'LEP',
                                'hh_efa_older': 'Older Adult',
                                'hh_efa_youth': 'Youth'}
col_list = ['EFA','Drove Alone', 'Shared Ride', 'Transit','Walk', 'Bike']

df_all['EFA'] = df_all['EFA'].map(col_dict)
df_all = df_all[col_list]
df_work['EFA'] = df_work['EFA'].map(col_dict)
df_work = df_work[col_list]
df_non_work['EFA'] = df_non_work['EFA'].map(col_dict)
df_non_work = df_non_work[col_list]
trip_all['EFA'] = trip_all['EFA'].map(col_dict)
trip_all = trip_all[col_list]
trip_work['EFA'] = trip_work['EFA'].map(col_dict)
trip_work = trip_work[col_list]
trip_non_work['EFA'] = trip_non_work['EFA'].map(col_dict)
trip_non_work = trip_non_work[col_list]

### Equity Focus Areas

:::{.panel-tabset}

#### All Purposes

In [26]:
df_all

Mode,EFA,Drove Alone,Shared Ride,Transit,Walk,Bike
equity_geog,,,,,,
Above Regional Average,Disability,42.5%,35.0%,3.6%,17.2%,1.7%
Below Regional Average,Disability,42.9%,35.6%,3.7%,16.1%,1.6%
Higher Share of Equity Population,Disability,39.0%,32.0%,3.6%,23.6%,1.9%
Above Regional Average,Older Adult,43.8%,35.6%,3.2%,15.9%,1.5%
Below Regional Average,Older Adult,40.8%,34.5%,3.9%,18.9%,1.8%
Higher Share of Equity Population,Older Adult,44.0%,34.3%,3.8%,16.4%,1.5%
Above Regional Average,LEP,41.5%,35.2%,3.8%,17.7%,1.7%
Below Regional Average,LEP,42.8%,34.3%,3.4%,17.9%,1.7%
Higher Share of Equity Population,LEP,41.0%,36.2%,4.5%,16.6%,1.8%
Above Regional Average,Income,41.6%,34.5%,3.7%,18.5%,1.7%
Below Regional Average,Income,43.8%,35.6%,3.4%,15.7%,1.6%
Higher Share of Equity Population,Income,37.1%,32.7%,4.7%,23.5%,2.1%
Above Regional Average,People of Color,39.8%,34.0%,3.9%,20.4%,1.9%
Below Regional Average,People of Color,44.7%,35.3%,3.2%,15.4%,1.5%
Higher Share of Equity Population,People of Color,39.0%,35.1%,4.7%,19.3%,1.9%
Above Regional Average,Youth,45.3%,38.5%,2.5%,12.3%,1.4%
Below Regional Average,Youth,39.6%,30.9%,4.9%,22.7%,2.0%
Higher Share of Equity Population,Youth,44.7%,41.6%,1.7%,10.6%,1.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

:::

#### Non-Work Purposes

In [27]:
df_non_work

Mode,EFA,Drove Alone,Shared Ride,Transit,Walk,Bike
equity_geog,,,,,,
Above Regional Average,Disability,38.8%,38.0%,3.5%,18.1%,1.7%
Below Regional Average,Disability,39.0%,38.9%,3.6%,16.8%,1.7%
Higher Share of Equity Population,Disability,35.6%,34.6%,3.5%,24.5%,1.9%
Above Regional Average,Older Adult,40.1%,38.7%,3.1%,16.6%,1.5%
Below Regional Average,Older Adult,36.8%,37.7%,3.9%,19.8%,1.9%
Higher Share of Equity Population,Older Adult,40.6%,37.0%,3.6%,17.3%,1.5%
Above Regional Average,LEP,37.7%,38.4%,3.8%,18.4%,1.7%
Below Regional Average,LEP,39.1%,37.3%,3.2%,18.7%,1.7%
Higher Share of Equity Population,LEP,36.9%,39.3%,4.5%,17.6%,1.8%
Above Regional Average,Income,37.8%,37.5%,3.6%,19.3%,1.7%
Below Regional Average,Income,39.9%,38.8%,3.3%,16.4%,1.6%
Higher Share of Equity Population,Income,33.3%,35.3%,4.6%,24.6%,2.1%
Above Regional Average,People of Color,36.1%,37.0%,3.9%,21.1%,1.9%
Below Regional Average,People of Color,40.8%,38.3%,3.0%,16.3%,1.5%
Higher Share of Equity Population,People of Color,35.1%,38.2%,4.7%,20.0%,1.9%
Above Regional Average,Youth,41.3%,41.7%,2.4%,13.2%,1.4%
Below Regional Average,Youth,36.0%,33.7%,4.8%,23.5%,1.9%
Higher Share of Equity Population,Youth,40.5%,45.1%,1.6%,11.4%,1.4%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

:::

#### Work

In [28]:
df_work

Mode,EFA,Drove Alone,Shared Ride,Transit,Walk,Bike
equity_geog,,,,,,
Above Regional Average,Disability,67.4%,15.3%,4.1%,11.6%,1.6%
Below Regional Average,Disability,67.7%,15.1%,4.1%,11.5%,1.6%
Higher Share of Equity Population,Disability,62.4%,14.2%,4.0%,17.4%,2.0%
Above Regional Average,Older Adult,68.7%,15.3%,3.5%,11.2%,1.4%
Below Regional Average,Older Adult,65.4%,15.0%,4.2%,13.5%,1.8%
Higher Share of Equity Population,Older Adult,68.2%,14.8%,5.0%,10.5%,1.4%
Above Regional Average,LEP,65.5%,15.2%,4.1%,13.6%,1.6%
Below Regional Average,LEP,67.1%,14.6%,4.1%,12.6%,1.6%
Higher Share of Equity Population,LEP,67.4%,16.2%,4.3%,10.3%,1.8%
Above Regional Average,Income,66.0%,15.2%,4.1%,13.0%,1.7%
Below Regional Average,Income,68.3%,15.1%,3.9%,11.3%,1.4%
Higher Share of Equity Population,Income,62.2%,14.8%,5.0%,15.8%,2.2%
Above Regional Average,People of Color,63.3%,14.7%,4.1%,16.1%,1.8%
Below Regional Average,People of Color,70.1%,15.2%,4.0%,9.2%,1.4%
Higher Share of Equity Population,People of Color,63.3%,15.3%,4.3%,15.2%,1.8%
Above Regional Average,Youth,72.8%,16.5%,3.3%,6.4%,1.2%
Below Regional Average,Youth,61.7%,13.7%,5.0%,17.5%,2.1%
Higher Share of Equity Population,Youth,74.5%,17.3%,2.3%,5.1%,0.9%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

:::

:::

:::

## Mode Share by Trip Destination

In [29]:
tour_rgc_dest = pd.read_csv(util.output_path / 'agg/dash/tour_rgc_dest.csv')
trip_rgc_dest = pd.read_csv(util.output_path / 'agg/dash/trip_rgc_dest.csv')

# order RGCs

# all individual centers
l = tour_rgc_dest['tour_d_rgc'].sort_values().unique().tolist()
l.remove('Not in RGC')
l.remove(np.nan)

# aggregated centers
geog_order = ["Region","In RGC","Not in RGC"]

# combine
geog_order.extend(l)

In [30]:
def get_rgc_location(df, dest_col):
    # regional data
    df_region = df.copy()
    df_region[dest_col] = "Region"

    # aggregated centers
    df_isrgc = df.copy()
    df_isrgc.loc[df_isrgc[dest_col]!="Not in RGC", dest_col] = "In RGC"


    df_rgc = pd.concat([
        df_region,
        df_isrgc,
    # 2025 notes:
    # 7 records in the data are missing both mode and and RGC values
    # remove these records
        df.loc[~df[dest_col].isna()]
        ])

    df_rgc[dest_col] = pd.Categorical(df_rgc[dest_col], ordered=True,
                    categories=geog_order)
    
    return df_rgc

df_tour = get_rgc_location(tour_rgc_dest, 'tour_d_rgc')
df_trip = get_rgc_location(trip_rgc_dest, 'trip_d_rgc')

:::{.panel-tabset}

### Regional Growth Center

In [31]:
def calc_mode_share_by_rgc(df_trip_geog, geog_col, mode_col, n_trip_col):

    df = df_trip_geog.pivot_table(columns=mode_col, index=geog_col, values=n_trip_col, aggfunc='sum', observed=True)

    df = df.apply(lambda x: x/ df_trip_geog.groupby(geog_col, observed=True)[n_trip_col].sum())

    return df

:::{.panel-tabset}

### All Trips

\[TRIP\] Mode Share for All Purposes by Regional Center (Destination Location)

In [32]:
calc_mode_share_by_rgc(df_trip, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.7%,20.7%,13.5%,41.4%,1.5%,0.4%,3.6%,17.3%
In RGC,2.1%,14.9%,8.7%,33.0%,0.6%,1.1%,7.5%,32.1%
Not in RGC,1.5%,22.3%,14.8%,43.7%,1.8%,0.3%,2.5%,13.2%
Auburn,1.3%,20.9%,11.9%,43.6%,0.6%,0.3%,3.4%,18.0%
Bellevue,2.1%,12.6%,8.0%,27.9%,0.5%,0.6%,6.9%,41.4%
Bothell Canyon Park,1.3%,22.6%,14.2%,49.0%,1.2%,0.3%,1.0%,10.4%
Bremerton,1.8%,15.6%,9.0%,45.2%,0.3%,0.4%,2.0%,25.9%
Burien,1.2%,21.3%,11.9%,41.9%,1.0%,0.3%,3.1%,19.1%
Everett,1.8%,16.7%,10.1%,36.1%,0.7%,0.4%,2.4%,31.8%
Federal Way,1.3%,21.8%,12.7%,39.6%,0.7%,0.3%,4.7%,18.8%
Greater Downtown Kirkland,1.5%,19.8%,11.2%,47.8%,0.9%,0.3%,3.1%,15.5%
Issaquah,1.2%,21.5%,12.2%,51.2%,0.5%,0.3%,1.0%,12.1%
Kent,1.3%,22.5%,13.9%,41.8%,0.5%,0.3%,3.5%,16.2%
Kirkland Totem Lake,1.6%,20.6%,12.1%,47.6%,0.7%,0.4%,2.4%,14.6%
Lakewood,1.6%,23.4%,13.1%,39.9%,0.5%,0.5%,1.2%,19.9%
Lynnwood,1.5%,21.2%,11.7%,43.3%,0.5%,0.4%,4.0%,17.4%
Puyallup Downtown,1.4%,22.5%,13.3%,42.8%,1.2%,0.4%,1.7%,16.8%
Puyallup South Hill,1.0%,22.3%,12.1%,51.2%,0.6%,0.3%,0.6%,12.0%
Redmond Downtown,2.2%,19.1%,12.3%,34.6%,1.1%,0.4%,3.9%,26.3%
Redmond-Overlake,2.0%,16.2%,10.5%,44.0%,0.6%,0.4%,5.2%,21.2%
Renton,1.7%,20.1%,12.2%,40.9%,0.9%,0.4%,3.0%,20.8%
SeaTac,1.7%,18.7%,12.2%,43.6%,1.0%,0.3%,6.0%,16.3%
Seattle Downtown,2.3%,7.7%,4.4%,18.9%,0.3%,2.6%,16.6%,47.3%
Seattle First Hill/Capitol Hill,3.0%,9.4%,5.2%,21.0%,0.4%,2.3%,10.5%,48.3%
Seattle Northgate,2.6%,16.9%,9.9%,33.4%,0.7%,0.5%,11.5%,24.5%
Seattle South Lake Union,2.8%,9.8%,5.2%,27.0%,0.2%,1.9%,9.4%,43.7%
Seattle University Community,3.3%,12.5%,7.0%,31.7%,0.4%,0.6%,15.3%,29.2%
Seattle Uptown,3.3%,11.2%,6.1%,24.9%,0.4%,1.4%,6.5%,46.2%
Silverdale,1.0%,21.8%,12.0%,51.1%,0.9%,0.3%,0.3%,12.6%
Tacoma Downtown,2.5%,13.8%,8.4%,30.6%,0.6%,0.6%,4.4%,39.1%
Tacoma Mall,2.2%,20.6%,12.1%,39.3%,0.7%,0.5%,2.1%,22.6%
Tukwila,1.4%,21.0%,12.7%,48.8%,0.3%,0.3%,3.7%,11.7%
University Place,1.8%,21.2%,12.4%,41.6%,1.2%,0.4%,1.3%,20.0%

\[TRIP\] Mode Share to Work by Regional Center (Destination Location)

### Work

In [33]:
df_trip_work = df_trip[df_trip['dpurp'] == 'Work'].copy()
calc_mode_share_by_rgc(df_trip_work, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.6%,9.2%,5.7%,66.2%,0.0%,0.8%,4.1%,12.3%
In RGC,1.9%,8.0%,5.1%,52.4%,0.0%,1.5%,8.0%,23.1%
Not in RGC,1.4%,10.0%,6.1%,74.9%,0.0%,0.4%,1.6%,5.5%
Auburn,1.4%,9.5%,5.5%,70.0%,NaN,0.3%,2.1%,11.2%
Bellevue,2.0%,8.0%,5.2%,50.1%,0.0%,0.7%,5.5%,28.6%
Bothell Canyon Park,1.3%,10.2%,6.5%,76.0%,NaN,0.4%,0.5%,5.2%
Bremerton,1.3%,9.1%,6.0%,72.1%,NaN,0.2%,1.5%,9.7%
Burien,1.5%,9.3%,5.6%,71.3%,NaN,0.4%,1.7%,10.1%
Everett,1.9%,8.9%,5.5%,61.8%,0.0%,0.4%,0.7%,20.7%
Federal Way,1.4%,10.1%,6.9%,67.7%,NaN,0.2%,2.8%,10.7%
Greater Downtown Kirkland,1.6%,9.4%,5.6%,73.9%,0.0%,0.4%,1.8%,7.3%
Issaquah,0.9%,10.2%,6.7%,74.0%,NaN,0.3%,0.9%,6.9%
Kent,1.5%,9.9%,6.8%,66.2%,NaN,0.4%,2.7%,12.5%
Kirkland Totem Lake,1.7%,10.3%,6.4%,72.4%,0.0%,0.5%,1.1%,7.6%
Lakewood,2.0%,10.1%,5.7%,68.9%,NaN,0.3%,1.0%,12.0%
Lynnwood,1.6%,9.6%,6.3%,71.0%,NaN,0.5%,1.9%,9.2%
Puyallup Downtown,1.5%,9.7%,6.2%,70.9%,NaN,0.5%,1.9%,9.4%
Puyallup South Hill,1.1%,9.5%,5.7%,76.2%,0.0%,0.3%,0.6%,6.6%
Redmond Downtown,2.2%,9.8%,6.1%,62.2%,0.0%,0.3%,2.6%,16.9%
Redmond-Overlake,1.5%,9.8%,6.6%,68.0%,NaN,0.5%,4.0%,9.6%
Renton,1.7%,10.3%,6.8%,67.2%,NaN,0.4%,1.8%,11.8%
SeaTac,1.4%,10.4%,6.8%,68.6%,NaN,0.4%,4.4%,7.8%
Seattle Downtown,1.9%,5.8%,3.5%,31.7%,NaN,3.1%,19.0%,35.0%
Seattle First Hill/Capitol Hill,2.4%,7.2%,4.2%,41.7%,0.0%,2.4%,7.7%,34.5%
Seattle Northgate,2.7%,10.3%,7.3%,62.2%,NaN,0.7%,5.3%,11.5%
Seattle South Lake Union,2.6%,6.9%,4.2%,44.6%,NaN,2.3%,7.5%,31.8%
Seattle University Community,2.3%,9.1%,5.7%,61.9%,NaN,1.0%,7.4%,12.6%
Seattle Uptown,2.8%,7.6%,4.5%,45.7%,NaN,1.7%,3.7%,34.0%
Silverdale,1.1%,8.3%,4.8%,75.1%,NaN,0.3%,0.4%,10.0%
Tacoma Downtown,2.4%,8.6%,5.6%,55.9%,NaN,0.5%,2.6%,24.4%
Tacoma Mall,2.5%,10.4%,6.3%,68.5%,0.0%,0.4%,1.4%,10.6%
Tukwila,1.3%,10.9%,7.0%,71.8%,NaN,0.5%,2.1%,6.3%
University Place,2.2%,9.7%,6.5%,70.2%,NaN,0.3%,0.9%,10.2%

### Non-Work

\[TRIP\] Mode Share for Non-work Purposes by Regional Center (Destination Location)

In [34]:
df_trip_non_work = df_trip[df_trip['dpurp'] != 'Work'].copy()
calc_mode_share_by_rgc(df_trip_non_work, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.7%,22.5%,14.7%,37.6%,1.7%,0.4%,3.5%,18.0%
In RGC,2.2%,17.0%,9.9%,26.9%,0.7%,1.0%,7.3%,34.9%
Not in RGC,1.5%,23.7%,15.8%,40.0%,2.0%,0.2%,2.6%,14.1%
Auburn,1.3%,22.7%,12.9%,39.4%,0.7%,0.3%,3.6%,19.1%
Bellevue,2.1%,14.4%,9.0%,19.5%,0.7%,0.6%,7.4%,46.2%
Bothell Canyon Park,1.4%,26.6%,16.7%,40.4%,1.5%,0.3%,1.1%,12.1%
Bremerton,2.0%,19.3%,10.7%,29.6%,0.4%,0.5%,2.3%,35.2%
Burien,1.2%,22.4%,12.5%,39.3%,1.0%,0.3%,3.3%,20.0%
Everett,1.8%,18.5%,11.2%,30.0%,0.9%,0.4%,2.8%,34.5%
Federal Way,1.3%,23.7%,13.6%,35.2%,0.8%,0.3%,5.0%,20.1%
Greater Downtown Kirkland,1.4%,22.3%,12.5%,41.4%,1.1%,0.3%,3.4%,17.6%
Issaquah,1.3%,25.1%,13.9%,44.0%,0.7%,0.2%,1.0%,13.7%
Kent,1.3%,25.4%,15.6%,36.2%,0.6%,0.3%,3.6%,17.1%
Kirkland Totem Lake,1.6%,23.1%,13.5%,41.3%,0.9%,0.3%,2.8%,16.4%
Lakewood,1.5%,25.5%,14.2%,35.3%,0.5%,0.5%,1.3%,21.1%
Lynnwood,1.5%,23.6%,12.8%,37.4%,0.7%,0.4%,4.5%,19.1%
Puyallup Downtown,1.4%,24.4%,14.4%,38.6%,1.3%,0.4%,1.6%,17.9%
Puyallup South Hill,0.9%,25.0%,13.4%,46.0%,0.7%,0.3%,0.6%,13.1%
Redmond Downtown,2.2%,20.5%,13.2%,30.5%,1.3%,0.4%,4.1%,27.7%
Redmond-Overlake,2.3%,19.5%,12.5%,31.4%,0.9%,0.4%,5.8%,27.3%
Renton,1.7%,22.6%,13.6%,34.2%,1.1%,0.4%,3.3%,23.1%
SeaTac,1.9%,22.2%,14.5%,33.1%,1.4%,0.3%,6.7%,19.9%
Seattle Downtown,2.5%,8.8%,5.0%,11.5%,0.5%,2.3%,15.2%,54.3%
Seattle First Hill/Capitol Hill,3.1%,9.8%,5.4%,16.7%,0.5%,2.3%,11.1%,51.1%
Seattle Northgate,2.6%,18.3%,10.5%,27.3%,0.9%,0.5%,12.8%,27.2%
Seattle South Lake Union,2.9%,11.1%,5.6%,18.6%,0.3%,1.7%,10.3%,49.4%
Seattle University Community,3.5%,13.2%,7.3%,24.7%,0.5%,0.5%,17.2%,33.1%
Seattle Uptown,3.4%,12.1%,6.5%,19.9%,0.5%,1.3%,7.1%,49.2%
Silverdale,1.0%,24.9%,13.6%,45.7%,1.1%,0.3%,0.3%,13.2%
Tacoma Downtown,2.5%,15.4%,9.2%,23.1%,0.8%,0.6%,4.9%,43.5%
Tacoma Mall,2.1%,22.8%,13.3%,33.0%,0.8%,0.6%,2.2%,25.2%
Tukwila,1.4%,24.7%,14.8%,40.3%,0.5%,0.3%,4.3%,13.7%
University Place,1.8%,22.6%,13.2%,38.1%,1.3%,0.4%,1.3%,21.3%

:::

:::

## Mode Share by Tour Destination

:::{.panel-tabset}

### RGC

:::{.panel-tabset}

### All Tours

\[TOUR\] Mode Share for All Purposes by Regional Center (Destination Location)

In [35]:
calc_mode_share_by_rgc(df_tour, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,Park,SOV,School Bus,TNC,Transit,Walk
tour_d_rgc,,,,,,,,,
Region,1.5%,21.2%,18.1%,0.2%,35.3%,2.4%,0.6%,5.2%,15.4%
In RGC,1.7%,16.4%,12.8%,0.7%,32.0%,0.7%,1.3%,11.4%,23.0%
Not in RGC,1.4%,23.0%,20.0%,0.1%,36.5%,3.0%,0.4%,3.0%,12.7%
Auburn,0.8%,23.0%,18.1%,0.1%,39.8%,0.4%,0.3%,3.7%,13.8%
Bellevue,1.6%,14.6%,11.8%,0.6%,31.3%,0.5%,0.7%,9.8%,29.1%
Bothell Canyon Park,1.1%,23.8%,21.4%,0.1%,41.4%,2.0%,0.5%,1.4%,8.3%
Bremerton,1.4%,20.6%,14.9%,0.1%,45.0%,0.2%,0.5%,1.0%,16.3%
Burien,0.9%,22.4%,17.4%,0.0%,36.4%,1.5%,0.3%,4.4%,16.7%
Everett,1.4%,19.6%,16.0%,0.1%,32.8%,0.8%,0.5%,3.7%,25.2%
Federal Way,0.9%,22.7%,18.1%,0.3%,35.9%,0.6%,0.4%,5.3%,16.0%
Greater Downtown Kirkland,1.2%,21.8%,17.0%,0.1%,43.6%,1.2%,0.3%,3.3%,11.4%
Issaquah,0.9%,23.1%,18.1%,0.1%,47.0%,0.8%,0.4%,1.4%,8.3%
Kent,0.9%,24.7%,20.5%,0.2%,37.1%,0.7%,0.4%,5.1%,10.6%
Kirkland Totem Lake,1.3%,21.8%,16.9%,0.1%,44.2%,0.9%,0.5%,3.5%,11.0%
Lakewood,1.2%,24.7%,19.2%,0.0%,36.7%,0.4%,0.5%,1.7%,15.6%
Lynnwood,1.2%,23.6%,17.4%,0.1%,39.7%,0.5%,0.5%,4.1%,12.9%
Puyallup Downtown,1.0%,25.5%,21.3%,0.0%,35.2%,2.4%,0.5%,2.1%,12.0%
Puyallup South Hill,0.8%,23.1%,17.7%,0.0%,47.5%,0.5%,0.4%,0.8%,9.2%
Redmond Downtown,1.3%,21.7%,18.2%,0.2%,29.7%,2.0%,0.3%,4.8%,21.8%
Redmond-Overlake,1.2%,17.5%,14.3%,0.5%,47.4%,0.3%,0.6%,5.3%,12.9%
Renton,1.1%,21.7%,18.2%,0.1%,38.1%,1.2%,0.5%,3.6%,15.5%
SeaTac,1.2%,19.7%,16.2%,0.9%,43.4%,0.6%,0.5%,6.3%,11.3%
Seattle Downtown,2.0%,8.5%,6.6%,2.2%,20.2%,0.5%,3.2%,26.8%,30.0%
Seattle First Hill/Capitol Hill,2.5%,11.7%,8.9%,0.7%,23.6%,0.7%,2.1%,13.9%,35.9%
Seattle Northgate,1.8%,19.0%,14.8%,0.3%,33.5%,1.0%,0.6%,10.8%,18.2%
Seattle South Lake Union,2.6%,11.7%,8.3%,0.8%,29.2%,0.2%,2.5%,13.2%,31.5%
Seattle University Community,2.7%,13.0%,9.8%,0.4%,31.2%,0.5%,0.6%,21.4%,20.4%
Seattle Uptown,2.6%,13.7%,9.5%,0.3%,26.1%,0.3%,1.5%,8.6%,37.4%
Silverdale,0.7%,24.7%,18.5%,0.0%,45.6%,1.6%,0.4%,0.3%,8.0%
Tacoma Downtown,2.0%,16.8%,13.6%,0.1%,31.0%,0.8%,0.6%,5.5%,29.5%
Tacoma Mall,1.7%,22.8%,17.3%,0.0%,38.8%,0.4%,0.5%,2.5%,15.9%
Tukwila,0.8%,22.9%,17.8%,0.2%,45.8%,0.1%,0.5%,5.1%,6.8%
University Place,1.5%,22.6%,17.3%,0.0%,36.7%,1.3%,0.5%,1.6%,18.5%

### Work

\[TOUR\] Mode Share to Work by Regional Center (Destination Location)

In [36]:
df_tour_work = df_tour[df_tour['pdpurp'] == 'Work'].copy()
calc_mode_share_by_rgc(df_tour_work, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,Park,SOV,TNC,Transit,Walk
tour_d_rgc,,,,,,,,
Region,1.6%,14.4%,11.6%,0.9%,58.2%,1.5%,5.0%,7.0%
In RGC,1.9%,12.1%,9.9%,1.7%,47.4%,2.6%,9.9%,14.4%
Not in RGC,1.3%,15.8%,12.6%,0.3%,65.1%,0.8%,1.8%,2.2%
Auburn,1.5%,15.6%,12.5%,0.4%,60.8%,0.7%,3.0%,5.5%
Bellevue,2.1%,12.4%,10.4%,1.2%,47.5%,1.2%,6.6%,18.7%
Bothell Canyon Park,1.2%,16.3%,13.7%,0.1%,65.8%,0.8%,0.7%,1.4%
Bremerton,1.2%,16.1%,12.7%,0.2%,63.4%,0.5%,1.5%,4.4%
Burien,1.4%,15.2%,12.3%,0.2%,63.2%,0.7%,1.9%,5.1%
Everett,2.2%,14.8%,12.5%,0.2%,54.8%,0.7%,0.8%,14.0%
Federal Way,1.5%,15.7%,13.6%,1.0%,59.4%,0.6%,3.0%,5.1%
Greater Downtown Kirkland,1.7%,15.2%,11.9%,0.2%,65.0%,0.5%,2.1%,3.4%
Issaquah,0.7%,16.2%,13.4%,0.2%,66.1%,0.7%,1.2%,1.5%
Kent,1.6%,16.5%,13.8%,0.6%,59.1%,0.7%,3.6%,4.1%
Kirkland Totem Lake,1.6%,16.5%,13.5%,0.2%,63.4%,0.7%,1.3%,2.8%
Lakewood,2.1%,15.8%,13.3%,0.1%,61.1%,0.4%,1.6%,5.4%
Lynnwood,1.8%,15.8%,12.7%,0.3%,62.8%,1.0%,1.9%,3.7%
Puyallup Downtown,1.3%,16.0%,13.6%,0.2%,61.2%,0.9%,3.3%,3.5%
Puyallup South Hill,1.1%,15.7%,13.3%,0.1%,66.0%,0.6%,0.9%,2.2%
Redmond Downtown,2.0%,15.3%,11.7%,0.7%,56.3%,0.6%,3.1%,10.4%
Redmond-Overlake,1.3%,14.8%,12.6%,0.7%,62.3%,0.9%,4.6%,2.8%
Renton,1.5%,15.9%,13.2%,0.3%,60.7%,0.8%,2.0%,5.6%
SeaTac,1.4%,15.8%,13.6%,1.5%,60.0%,0.7%,4.4%,2.6%
Seattle Downtown,1.9%,7.5%,6.0%,4.1%,30.2%,5.3%,23.4%,21.8%
Seattle First Hill/Capitol Hill,2.3%,10.6%,8.5%,1.9%,39.3%,4.1%,9.1%,24.1%
Seattle Northgate,2.6%,14.7%,12.7%,0.9%,58.1%,1.1%,4.5%,5.4%
Seattle South Lake Union,2.7%,10.6%,8.2%,1.5%,42.4%,4.2%,8.4%,22.0%
Seattle University Community,2.1%,13.9%,11.2%,1.3%,57.3%,1.5%,7.0%,5.5%
Seattle Uptown,2.9%,11.6%,8.8%,0.8%,43.4%,2.9%,4.4%,25.2%
Silverdale,1.1%,14.7%,11.3%,0.2%,68.2%,0.6%,0.4%,3.5%
Tacoma Downtown,2.5%,14.3%,11.8%,0.3%,51.3%,0.9%,3.6%,15.3%
Tacoma Mall,2.4%,16.4%,13.1%,0.1%,61.4%,0.6%,2.0%,4.0%
Tukwila,1.2%,16.9%,13.9%,0.4%,63.2%,0.8%,2.5%,1.0%
University Place,2.2%,15.3%,12.9%,0.1%,62.1%,0.6%,1.3%,5.5%

### Non-Work

\[TOUR\] Mode Share for Non-work Purposes by Regional Center (Destination Location)

In [37]:
df_tour_non_work = df_tour[df_tour['pdpurp'] != 'Work'].copy()
calc_mode_share_by_rgc(df_tour_non_work, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
tour_d_rgc,,,,,,,,
Region,1.5%,23.9%,20.6%,26.5%,3.3%,0.3%,5.3%,18.6%
In RGC,1.5%,19.3%,14.9%,21.2%,1.2%,0.5%,12.4%,29.0%
Not in RGC,1.4%,25.1%,22.2%,28.0%,3.9%,0.2%,3.3%,15.8%
Auburn,0.5%,25.5%,20.1%,32.7%,0.6%,0.2%,3.9%,16.6%
Bellevue,1.1%,16.7%,13.1%,15.9%,0.9%,0.3%,12.9%,39.0%
Bothell Canyon Park,1.1%,29.1%,26.9%,24.0%,3.5%,0.3%,2.0%,13.2%
Bremerton,1.6%,25.5%,17.4%,24.9%,0.4%,0.6%,0.4%,29.4%
Burien,0.8%,23.7%,18.3%,31.7%,1.7%,0.2%,4.8%,18.8%
Everett,1.1%,21.9%,17.5%,22.7%,1.2%,0.4%,5.1%,30.2%
Federal Way,0.6%,25.2%,19.6%,27.6%,0.8%,0.3%,6.1%,19.8%
Greater Downtown Kirkland,0.9%,25.3%,19.8%,32.3%,1.8%,0.2%,4.0%,15.7%
Issaquah,0.9%,27.5%,21.1%,34.7%,1.3%,0.3%,1.5%,12.7%
Kent,0.6%,27.6%,22.9%,29.0%,1.0%,0.3%,5.6%,12.9%
Kirkland Totem Lake,1.1%,24.7%,18.8%,33.5%,1.3%,0.3%,4.7%,15.6%
Lakewood,0.9%,27.3%,21.0%,29.4%,0.5%,0.5%,1.7%,18.6%
Lynnwood,1.0%,26.7%,19.2%,30.5%,0.7%,0.3%,5.0%,16.6%
Puyallup Downtown,0.9%,27.9%,23.2%,28.6%,3.0%,0.4%,1.8%,14.1%
Puyallup South Hill,0.7%,25.7%,19.1%,41.3%,0.6%,0.3%,0.7%,11.6%
Redmond Downtown,1.0%,23.9%,20.5%,20.5%,2.7%,0.3%,5.4%,25.7%
Redmond-Overlake,1.0%,22.3%,17.4%,20.4%,0.8%,0.2%,6.7%,31.2%
Renton,0.8%,25.4%,21.5%,23.4%,2.0%,0.3%,4.7%,21.9%
SeaTac,0.9%,24.9%,19.8%,21.2%,1.3%,0.2%,8.8%,22.9%
Seattle Downtown,2.1%,9.8%,7.3%,8.2%,1.1%,0.7%,30.9%,39.9%
Seattle First Hill/Capitol Hill,2.6%,12.4%,9.1%,14.8%,1.1%,0.9%,16.6%,42.4%
Seattle Northgate,1.3%,21.3%,16.0%,20.1%,1.5%,0.4%,14.2%,25.2%
Seattle South Lake Union,2.5%,12.9%,8.4%,15.3%,0.5%,0.6%,18.3%,41.5%
Seattle University Community,3.0%,12.5%,9.1%,18.4%,0.7%,0.2%,28.4%,27.7%
Seattle Uptown,2.3%,14.9%,10.0%,15.8%,0.5%,0.7%,11.2%,44.6%
Silverdale,0.6%,28.2%,21.0%,37.9%,2.2%,0.3%,0.3%,9.6%
Tacoma Downtown,1.6%,18.4%,14.9%,17.5%,1.4%,0.5%,6.9%,38.9%
Tacoma Mall,1.4%,25.6%,19.2%,28.7%,0.6%,0.5%,2.8%,21.2%
Tukwila,0.6%,27.0%,20.5%,33.6%,0.2%,0.2%,6.9%,10.9%
University Place,1.2%,25.0%,18.7%,28.5%,1.7%,0.5%,1.6%,22.7%

:::

:::