In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to9": 5, "9to15": 9, "15to18": 15, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "Household"
date: today
---

In [2]:
import pandas as pd
from pathlib import Path
import util

pd.set_option('display.float_format', '{:,.0%}'.format)

In [3]:


# list of equity geographies
equity_geogs = util.summary_config['hh_equity_geogs']
# not_equity_geogs = ["NOT in " + item for item in equity_geogs]

## Household VMT

In [4]:
# vmt data
df_vmt = pd.read_csv(util.output_path / 'agg/dash/person_vmt.csv')

# add home RGC
df_vmt['is_rgc'] = 'Not in RGC'
df_vmt.loc[df_vmt['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

# Select only drivers (dorp = 1) and auto trips
df_vmt = df_vmt[df_vmt['mode'].isin(['SOV','HOV2','HOV3+']) & (df_vmt['dorp'] == 1)].copy()

df_hh = pd.read_csv(util.output_path / 'agg/dash/hh_geog.csv')
df_hh['is_rgc'] = 'Not in RGC'
df_hh.loc[df_hh['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

def vmt_per_hh(df_vmt, df_hh, geog, map=False):
    _df_vmt = df_vmt.groupby(geog).sum()[['travdist_wt']]
    df_hh = df_hh.groupby(geog).sum()[['hhexpfac']]

    df = _df_vmt.merge(df_hh, left_index=True, right_index=True)

    if map:
        df.index = df.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })
    
    
    df.loc['Region',:] = df.sum(axis=0)
    df['Average Miles per Household'] = df['travdist_wt']/df['hhexpfac']

    
    return df[['Average Miles per Household']]

:::{.panel-tabset}

### County

In [5]:
pd.set_option('display.float_format', '{:,.1f}'.format)
vmt_per_hh(df_vmt, df_hh, "hh_county")

                Average Miles per Household
hh_county
King                                   32.3
Kitsap                                 35.3
Outside Region                         45.9
Pierce                                 40.0
Snohomish                              43.7
Region                                 36.1

### Regional Growth Center

In [6]:
vmt_per_hh(df_vmt, df_hh, "is_rgc")

            Average Miles per Household
is_rgc
In RGC                             10.6
Not in RGC                         38.8
Region                             36.1

In [7]:
vmt_per_hh(df_vmt, df_hh, "hh_rgc")

                                 Average Miles per Household
hh_rgc
Auburn                                                  24.8
Bellevue                                                12.1
Bothell Canyon Park                                     36.8
Bremerton                                               13.8
Burien                                                  24.9
Everett                                                 15.0
Federal Way                                             29.3
Greater Downtown Kirkland                               21.6
Kent                                                    21.6
Kirkland Totem Lake                                     25.0
Lakewood                                                22.2
Lynnwood                                                24.8
Not in RGC                                              38.8
Puyallup Downtown                                       18.9
Puyallup South Hill                                     25.8
Redmond Downtown                                        18.8
Redmond-Overlake                                        16.7
Renton                                                  21.5
SeaTac                                                  26.6
Seattle Downtown                                         2.7
Seattle First Hill/Capitol Hill                          4.6
Seattle Northgate                                       17.0
Seattle South Lake Union                                 4.5
Seattle University Community                             9.3
Seattle Uptown                                           7.4
Silverdale                                              13.9
Tacoma Downtown                                         12.3
Tacoma Mall                                             16.2
Tukwila                                                 19.6
University Place                                        23.1
Region                                                  36.1

### Regional Geography

In [8]:
pd.set_option('display.float_format', '{:,.1f}'.format)
vmt_per_hh(df_vmt, df_hh, "hh_rg_proposed")

                                   Average Miles per Household
hh_rg_proposed
Cities and Towns                                          49.8
Core Cities                                               36.0
High Capacity Transit Communities                         39.3
Metropolitan Cities                                       21.7
Rural Areas                                               60.4
Urban Unincorporated Areas                                46.6
Region                                                    36.1

### Equity Focus Area

In [9]:
efa_names = {
    "People of Color": "hh_efa_poc",
    "Income": "hh_efa_pov200",
    "LEP": "hh_efa_lep",
    "Disability": "hh_efa_dis",
    "Older Adults": "hh_efa_older",
    "Youth": "hh_efa_youth"
}

df = pd.DataFrame()
for name, col in efa_names.items():
    df[name] = vmt_per_hh(df_vmt, df_hh, col, map=True)
df

,People of Color,Income,LEP,Disability,Older Adults,Youth
hh_efa_poc,,,,,,
Below Regional Average,38.7,38.8,36.4,37.4,34.7,29.7
Above Regional Average,33.0,34.0,36.3,36.2,38.1,42.5
Higher Share of Equity Population,33.0,28.6,34.6,31.4,36.7,47.9
Region,36.1,36.1,36.1,36.1,36.1,36.1

:::

## Delay

:::{.panel-tabset}
### County

In [10]:
df = pd.read_csv(util.output_path / 'agg/dash/trip_time_total.csv')
df = df[(df['mode'].isin(['SOV','HOV2','HOV3+'])&(df['dorp']==1))]

In [11]:
pd.options.display.float_format = '{:0,.1f}'.format
# Hours of delay for households in these locations
# df[['Total Delay Hours']]

def delay_per_hh(geog, map=False):

    df_hh = pd.read_csv(util.output_path / 'agg/dash/hh_geog.csv')
    df_hh['is_rgc'] = 'Not in RGC'
    df_hh.loc[df_hh['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

    df = pd.read_csv(util.output_path / 'agg/dash/trip_time_total.csv')
    df['is_rgc'] = 'Not in RGC'
    df.loc[df['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'
    df = df[(df['mode'].isin(['SOV','HOV2','HOV3+'])&(df['dorp']==1))]
    df = df.groupby(geog).sum()[['travtime_wt']]

    df2 = pd.read_csv(util.output_path / 'agg/dash/trip_sov_ff_time.csv')
    df2['is_rgc'] = 'Not in RGC'
    df2.loc[df2['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'
    df2 = df2[(df2['mode'].isin(['SOV','HOV2','HOV3+'])&(df2['dorp']==1))]
    df2 = df2.groupby(geog).sum()[['sov_ff_time_wt']]
    df = df2.merge(df, on=geog)

    # Hours of delay from travel time
    df['Total Delay Hours'] = (df['travtime_wt'] - df['sov_ff_time_wt'])/60
    # Set any negative delay to 0
    df.loc[df['Total Delay Hours'] < 0, 'Total Delay Hours'] = 0

    df_hh = df_hh.groupby(geog).sum()[['hhexpfac']]
    
    
    # df.loc['Region',:] = df.sum(axis=0)
    # df['Average Miles per Household'] = df['travdist_wt']/df['hhexpfac']


    df = df.merge(df_hh, left_index=True, right_index=True)
    
    df['Average Minutes of Delay per HH'] = df['Total Delay Hours']/df['hhexpfac']*60

    if map:
        df.index = df.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

    df['Annual Hours of Delay per HH'] = df['Average Minutes of Delay per HH']*util.summary_config['weekday_to_annual']/60

    df[['Total Delay Hours',
        'Annual Hours of Delay per HH']] = df[['Total Delay Hours', 'Annual Hours of Delay per HH']].astype(int).map('{:,}'.format)


    return df[['Total Delay Hours','Average Minutes of Delay per HH','Annual Hours of Delay per HH']]

df = delay_per_hh('hh_county')
df

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
hh_county,,,
King,"102,104",6.4,34
Kitsap,"5,457",3.0,16
Outside Region,0,2.0,10
Pierce,"35,642",6.1,32
Snohomish,"45,662",8.6,45

### Regional Growth Center

In [12]:
delay_per_hh('is_rgc')

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
is_rgc,,,
In RGC,"5,140",1.9,9
Not in RGC,"183,726",7.0,37

In [13]:
delay_per_hh('hh_rgc')

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
hh_rgc,,,
Auburn,56,3.4,18
Bellevue,454,2.8,14
Bothell Canyon Park,60,12.7,67
Bremerton,65,2.4,12
Burien,123,3.8,20
Everett,123,1.9,10
Federal Way,13,3.4,17
Greater Downtown Kirkland,448,6.1,32
Kent,63,3.9,20
Kirkland Totem Lake,476,6.9,37
Lakewood,11,2.4,12
Lynnwood,225,6.0,32
Not in RGC,"183,726",7.0,37
Puyallup Downtown,23,2.5,13
Puyallup South Hill,81,3.8,20
Redmond Downtown,295,3.4,17
Redmond-Overlake,178,4.1,21
Renton,263,5.2,27
SeaTac,364,4.6,24
Seattle Downtown,0,0.0,0
Seattle First Hill/Capitol Hill,299,0.5,2
Seattle Northgate,318,4.0,21
Seattle South Lake Union,75,0.5,2
Seattle University Community,550,2.6,13
Seattle Uptown,119,0.9,4
Silverdale,3,0.2,0
Tacoma Downtown,175,1.1,5
Tacoma Mall,118,2.4,12
Tukwila,20,3.2,17
University Place,207,3.7,19

### Regional Geography

In [14]:
delay_per_hh('hh_rg_proposed')

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
hh_rg_proposed,,,
Cities and Towns,"18,070",8.0,42
Core Cities,"47,121",7.3,38
High Capacity Transit Communities,"50,239",8.4,44
Metropolitan Cities,"40,513",4.1,21
Rural Areas,"24,238",7.2,38
Urban Unincorporated Areas,"8,684",8.4,44

### Equity Focus Areas

In [15]:
df = pd.DataFrame()
for name, col in efa_names.items():
    _df = delay_per_hh(col, map=True)
    _df['Group'] = name
    df = pd.concat([df, _df])

df = df.reset_index()
df.rename(columns={'index':'EFA Type'}, inplace=True)

df[['Group', 'EFA Type', 'Total Delay Hours', 'Average Minutes of Delay per HH', 'Annual Hours of Delay per HH']]

,Group,EFA Type,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
0,People of Color,Below Regional Average,"100,609",6.4,34
1,People of Color,Above Regional Average,"56,421",6.8,36
2,People of Color,Higher Share of Equity Population,"31,836",6.5,34
3,Income,Below Regional Average,"125,070",7.2,38
4,Income,Above Regional Average,"43,561",5.9,31
5,Income,Higher Share of Equity Population,"20,235",4.9,25
6,LEP,Below Regional Average,"108,896",6.0,31
7,LEP,Above Regional Average,"45,435",7.6,40
8,LEP,Higher Share of Equity Population,"34,534",7.2,38
9,Disability,Below Regional Average,"115,842",7.4,39
10,Disability,Above Regional Average,"52,931",6.0,32
11,Disability,Higher Share of Equity Population,"20,093",4.5,24
12,Older Adults,Below Regional Average,"104,140",6.9,36
13,Older Adults,Above Regional Average,"63,284",6.4,34
14,Older Adults,Higher Share of Equity Population,"21,441",5.5,29
15,Youth,Below Regional Average,"87,320",5.5,29
16,Youth,Above Regional Average,"70,215",7.4,39
17,Youth,Higher Share of Equity Population,"31,330",8.7,46

:::

## Vehicle Ownership Distribution

percentage of households by number of vehicles available, by geography

In [16]:
pd.set_option('display.float_format', '{:,.0%}'.format)

hh = pd.read_csv(util.output_path / 'agg/dash/auto_ownership_efa.csv')
df_hh = hh.copy()
df_hh = df_hh[df_hh['hh_county']!="Outside Region"].copy()
# add home RGC
df_hh['is_rgc'] = 'Not in RGC'
df_hh.loc[df_hh['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

equity_geogs = ['hh_efa_dis', 'hh_efa_older', 'hh_efa_lep', 'hh_efa_pov200', 'hh_efa_poc', 'hh_efa_youth']
df_hh[equity_geogs] = df_hh[equity_geogs].apply(lambda x: x.\
        map({0: 'Below Regional Average', 
             1: 'Above Regional Average', 
             2: 'Higher Share of Equity Population'}))

df_hh['hhvehs'] = df_hh['hhvehs'].map({0:"0 vehicle",
                                       1:"1 vehicle",
                                       2:"2 vehicles",
                                       3:"3 vehicles",
                                       4:"4 or more vehicles"})

In [17]:
def stat_by_geog(df, geog):
    """
    Function to calculate statistics by geography and vehicle ownership.
    """
    
    # Group by equity geography and vehicle ownership
    df_grouped = df.groupby([geog, 'hhvehs'], as_index=False)['hhexpfac'].sum()
    
    # Calculate total households in each equity geography
    total_hh = df.groupby([geog], as_index=False)['hhexpfac'].sum().rename(columns={'hhexpfac': 'total_hh'})
    
    # Merge the grouped data with total households
    df_merged = df_grouped.merge(total_hh, on=geog)
    
    # Calculate percentage of households with the specified vehicle ownership
    df_merged['percentage'] = df_merged['hhexpfac'] / df_merged['total_hh']
    
    return df_merged.pivot(index=geog, columns='hhvehs', values='percentage')

:::{.panel-tabset}

### County

In [18]:
df_region = df_hh.groupby(['hhvehs'], as_index=False)['hhexpfac'].sum()
df_region['percentage'] = df_region['hhexpfac'] / df_hh['hhexpfac'].sum()
df_region['hh_county'] = 'Region'

In [19]:
df = stat_by_geog(df_hh, 'hh_county')
pd.concat([df_region.pivot(index='hh_county', columns='hhvehs', values='percentage'),df])

hhvehs     0 vehicle  1 vehicle  2 vehicles  3 vehicles  4 or more vehicles
hh_county
Region            8%        33%         37%         15%                  8%
King             10%        36%         34%         13%                  7%
Kitsap            4%        27%         39%         20%                 10%
Pierce            5%        29%         39%         17%                  9%
Snohomish         4%        28%         40%         18%                 10%

### Regional Geography

In [20]:
df = stat_by_geog(df_hh, 'hh_rg_proposed')
df

hhvehs,0 vehicle,1 vehicle,2 vehicles,3 vehicles,4 or more vehicles
hh_rg_proposed,,,,,
Cities and Towns,2%,24%,43%,20%,10%
Core Cities,5%,34%,38%,15%,8%
High Capacity Transit Communities,4%,29%,40%,17%,9%
Metropolitan Cities,15%,42%,29%,9%,4%
Rural Areas,1%,16%,41%,27%,14%
Urban Unincorporated Areas,2%,22%,45%,20%,11%

### Regional Growth Center

In [21]:
df = stat_by_geog(df_hh, 'is_rgc')
df

hhvehs      0 vehicle  1 vehicle  2 vehicles  3 vehicles  4 or more vehicles
is_rgc
In RGC            32%        48%         15%          3%                  1%
Not in RGC         5%        31%         39%         16%                  9%

In [22]:
df = stat_by_geog(df_hh, 'hh_rgc')
df

hhvehs,0 vehicle,1 vehicle,2 vehicles,3 vehicles,4 or more vehicles
hh_rgc,,,,,
Auburn,19%,47%,22%,7%,5%
Bellevue,24%,56%,16%,3%,1%
Bothell Canyon Park,1%,36%,41%,14%,7%
Bremerton,19%,50%,22%,6%,4%
Burien,15%,49%,24%,7%,4%
Everett,20%,53%,20%,4%,2%
Federal Way,13%,50%,25%,7%,5%
Greater Downtown Kirkland,11%,53%,27%,6%,2%
Kent,20%,49%,21%,8%,3%
Kirkland Totem Lake,9%,49%,30%,8%,4%
Lakewood,11%,51%,24%,8%,6%
Lynnwood,15%,44%,28%,8%,5%
Not in RGC,5%,31%,39%,16%,9%
Puyallup Downtown,15%,52%,20%,9%,4%
Puyallup South Hill,12%,42%,30%,10%,6%
Redmond Downtown,13%,58%,23%,4%,2%
Redmond-Overlake,14%,58%,22%,4%,2%
Renton,17%,55%,21%,5%,2%
SeaTac,11%,49%,27%,7%,5%
Seattle Downtown,48%,43%,8%,1%,0%
Seattle First Hill/Capitol Hill,44%,44%,10%,1%,0%
Seattle Northgate,21%,51%,22%,4%,2%
Seattle South Lake Union,35%,52%,11%,1%,0%
Seattle University Community,37%,44%,14%,3%,2%
Seattle Uptown,28%,55%,14%,2%,1%
Silverdale,13%,46%,27%,10%,4%
Tacoma Downtown,28%,51%,16%,3%,2%
Tacoma Mall,22%,48%,22%,5%,3%
Tukwila,16%,52%,24%,6%,3%
University Place,8%,48%,31%,9%,4%

### Equity Focus Areas

In [23]:
df = pd.DataFrame()
for name, col in efa_names.items():
    _df = stat_by_geog(df_hh,col).reset_index()
    _df['Group'] = name
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

hhvehs                                             0 vehicle  1 vehicle  \
Group           EFA Type
People of Color Above Regional Average                   10%        34%
                Below Regional Average                    6%        31%
                Higher Share of Equity Population        10%        36%
Income          Above Regional Average                    8%        34%
                Below Regional Average                    6%        30%
                Higher Share of Equity Population        13%        39%
LEP             Above Regional Average                    8%        32%
                Below Regional Average                    8%        32%
                Higher Share of Equity Population         7%        36%
Disability      Above Regional Average                    8%        34%
                Below Regional Average                    6%        31%
                Higher Share of Equity Population        11%        35%
Older Adults    Above Regional Average                    6%        31%
                Below Regional Average                    9%        34%
                Higher Share of Equity Population         7%        31%
Youth           Above Regional Average                    4%        28%
                Below Regional Average                   11%        38%
                Higher Share of Equity Population         3%        24%

hhvehs                                             2 vehicles  3 vehicles  \
Group           EFA Type
People of Color Above Regional Average                    35%         14%
                Below Regional Average                    38%         17%
                Higher Share of Equity Population         34%         13%
Income          Above Regional Average                    35%         14%
                Below Regional Average                    39%         17%
                Higher Share of Equity Population         31%         11%
LEP             Above Regional Average                    37%         15%
                Below Regional Average                    37%         16%
                Higher Share of Equity Population         35%         13%
Disability      Above Regional Average                    35%         15%
                Below Regional Average                    38%         16%
                Higher Share of Equity Population         32%         13%
Older Adults    Above Regional Average                    37%         17%
                Below Regional Average                    36%         14%
                Higher Share of Equity Population         36%         17%
Youth           Above Regional Average                    40%         18%
                Below Regional Average                    33%         12%
                Higher Share of Equity Population         43%         20%

hhvehs                                             4 or more vehicles
Group           EFA Type
People of Color Above Regional Average                             8%
                Below Regional Average                             9%
                Higher Share of Equity Population                  7%
Income          Above Regional Average                             8%
                Below Regional Average                             9%
                Higher Share of Equity Population                  6%
LEP             Above Regional Average                             8%
                Below Regional Average                             8%
                Higher Share of Equity Population                  8%
Disability      Above Regional Average                             8%
                Below Regional Average                             8%
                Higher Share of Equity Population                  8%
Older Adults    Above Regional Average                             9%
                Below Regional Average                             7%
                Higher Share of Equity Population                  9%
Youth           Above Regional Average                            10%
                Below Regional Average                             7%
                Higher Share of Equity Population                 10%

:::