In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "daysim-validation-notebook": ["all_tour_mode", "all_trip_mode", "auto_ownership", "day_pattern", "escort_tour_mode", "escort_trip_mode", "households", "intermediate_stop_generation", "other_home_based_tour_mode", "other_home_based_trip_mode", "persons", "school_location", "school_tour_mode", "school_trip_mode", "telecommute", "time_choice", "tours", "tour_destination", "transit_pass_ownership", "trips", "trip_destination", "workbased_subtour_generation", "workbased_subtour_mode", "work_location", "work_tour_mode", "work_trip_mode"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to6": 5, "6to7": 6, "7to8": 7, "8to9": 8, "9to10": 9, "10to14": 10, "14to15": 14, "15to16": 15, "16to17": 16, "17to18": 17, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "Mode Share"
date: today
---

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import util

pd.set_option('display.float_format', '{:,.1%}'.format)

In [3]:
# add trip type to trip tables
def prep_trip_df(trip):
    """Mode shares will represent shares across Drive Alone, Shared Ride, 
       public transit, and walk and bike trips only. 
    """
    df_trip = trip.copy()
    df_trip.rename(columns={'mode':'Mode'}, inplace=True)
    df_trip['Trip Type'] = 'Non-Work'
    df_trip.loc[df_trip['dpurp'] == 'Work', 'Trip Type'] = 'Work'

    # add all tripa
    df = df_trip.copy()
    df['Trip Type'] = 'All Trips'
    df_trip = pd.concat([df_trip.sort_values('Trip Type'), df], ignore_index=True)

    # Exclude TNC, School Bus, and Other modes
    df_trip = df_trip[~df_trip['Mode'].isin(['TNC', 'School Bus', 'Other'])]

    # Aggregate modes
    df_trip['Mode'] = df_trip['Mode'].replace({
        'SOV': 'Drove Alone',
        'HOV2': 'Shared Ride',
        'HOV3+': 'Shared Ride',
        'Transit': 'Transit',
        'Walk': 'Walk',
        'Bike': 'Bike',
    })

    return df_trip

In [4]:
person = pd.read_csv(util.output_path / 'agg/dash/person_geog.csv')

# counties
trip_county = prep_trip_df(pd.read_csv(util.output_path / 'agg/dash/mode_share_county.csv'))
# remove "Outside Region"
trip_county = trip_county[trip_county['hh_county'] != 'Outside Region']
# regional geographies
trip_rg = prep_trip_df(pd.read_csv(util.output_path / 'agg/dash/mode_share_rg.csv'))
# centers
trip_rgc = pd.read_csv(util.output_path / 'agg/dash/mode_share_rgc.csv')
# add all RGCs
df = trip_rgc[trip_rgc['hh_rgc'] != 'Not in RGC'].groupby(['dpurp','mode']).sum()[['trexpfac']].reset_index()
df['hh_rgc'] = 'All RGCs'
trip_rgc = pd.concat([df, trip_rgc])
trip_rgc = prep_trip_df(trip_rgc)

In [5]:
# equity geographies
equity_geogs = util.summary_config['hh_equity_geogs']
trip_equity_geog = pd.DataFrame()
for geog in equity_geogs:
    df = prep_trip_df(pd.read_csv(util.output_path/ ('agg/dash/mode_share_'+geog+'.csv')))
    df['equity_geog'] = df[geog].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'})
    
    trip_equity_geog = pd.concat([trip_equity_geog, df[['dpurp', 'Mode', 'equity_geog', 'trexpfac', 'Trip Type']]])

## regional mode share

In [6]:
df1 = trip_county.groupby(['Trip Type','Mode'],as_index=False)['trexpfac'].sum()
df2 = trip_county.groupby(['Trip Type'],as_index=False)['trexpfac'].sum()
df2.rename(columns={'trexpfac':'total_trips'}, inplace=True)

df = df1.merge(df2, on='Trip Type')
df['mode_share'] = df['trexpfac'] / df['total_trips']

df.pivot_table(columns='Mode', index='Trip Type', values='mode_share')

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
Trip Type
All Trips  1.5%        45.4%        36.2%     2.2% 14.7%
Non-Work   1.5%        41.2%        39.4%     2.2% 15.6%
Work       1.4%        72.0%        15.4%     2.3%  9.0%

## trip mode share by home location

:::{.panel-tabset}

### County

In [7]:
def calc_mode_share(df_trip, geog):
    
    # num trips by mode
    df1 = df_trip.groupby([geog, 'Trip Type', 'Mode'],as_index=False)['trexpfac'].sum()
    # num trips
    df2 = df_trip.groupby([geog, 'Trip Type'],as_index=False)['trexpfac'].sum()
    df2.rename(columns={'trexpfac':'total_trips'}, inplace=True)

    df = df1.merge(df2, on=[geog, 'Trip Type'])
    # mode share
    df['mode_share'] = df['trexpfac'] / df['total_trips']

    # mode share by trip type
    df_all = df.loc[df['Trip Type']=="All Trips"].pivot_table(columns='Mode', index=geog, values='mode_share')
    df_work = df.loc[df['Trip Type']=="Work"].pivot_table(columns='Mode', index=geog, values='mode_share')
    df_non_work = df.loc[df['Trip Type']=="Non-Work"].pivot_table(columns='Mode', index=geog, values='mode_share')
    # num trips by trip type
    trip_all = df.loc[df['Trip Type']=="All Trips"].pivot_table(columns='Mode', index=geog, values='trexpfac')
    trip_work = df.loc[df['Trip Type']=="Work"].pivot_table(columns='Mode', index=geog, values='trexpfac')
    trip_non_work = df.loc[df['Trip Type']=="Non-Work"].pivot_table(columns='Mode', index=geog, values='trexpfac')

    return df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work


df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work = calc_mode_share(trip_county,'hh_county')

:::{.panel-tabset}

#### All Purposes

In [8]:
df_all

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
hh_county
King       1.7%        44.2%        34.1%     3.3% 16.7%
Kitsap     1.2%        45.7%        37.0%     1.6% 14.5%
Pierce     1.4%        46.0%        39.5%     0.8% 12.4%
Snohomish  1.3%        47.8%        38.4%     0.8% 11.7%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [9]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [10]:
df_non_work

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
hh_county
King       1.7%        40.1%        37.3%     3.3% 17.6%
Kitsap     1.3%        42.2%        39.8%     1.2% 15.5%
Pierce     1.5%        41.9%        42.6%     0.7% 13.3%
Snohomish  1.4%        43.4%        41.7%     0.9% 12.7%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [11]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [12]:
df_work

Mode       Bike  Drove Alone  Shared Ride  Transit  Walk
hh_county
King       1.7%        69.1%        14.8%     2.9% 11.6%
Kitsap     0.9%        71.6%        15.1%     5.0%  7.3%
Pierce     1.1%        76.0%        16.2%     1.2%  5.5%
Snohomish  1.0%        77.1%        16.4%     0.7%  4.9%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [13]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Regional Growth Center

:::{.panel-tabset}

#### All Purposes

In [14]:
df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_rgc, 'hh_rgc')

df_all

Mode                             Bike  Drove Alone  Shared Ride  Transit  Walk
hh_rgc
All RGCs                         3.1%        30.0%        16.7%     6.3% 43.9%
Auburn                           2.5%        38.2%        30.3%     3.8% 25.2%
Bellevue                         2.7%        32.2%        17.0%     3.8% 44.3%
Bothell Canyon Park              1.4%        50.8%        33.9%     0.4% 13.5%
Bremerton                        2.7%        35.6%        22.2%     2.8% 36.7%
Burien                           1.9%        44.2%        27.0%     3.2% 23.7%
Everett                          2.0%        38.8%        20.6%     2.1% 36.5%
Federal Way                      2.5%        36.7%        35.6%     1.8% 23.3%
Greater Downtown Kirkland        1.7%        46.7%        26.3%     4.2% 21.1%
Kent                             1.9%        37.2%        30.7%     4.3% 25.8%
Kirkland Totem Lake              1.8%        50.8%        29.5%     1.7% 16.2%
Lakewood                         2.6%        41.1%        30.7%     0.8% 24.8%
Lynnwood                         2.0%        43.7%        31.8%     2.2% 20.3%
Not in RGC                       1.4%        46.5%        37.6%     1.9% 12.6%
Puyallup Downtown                1.5%        41.4%        28.4%     1.9% 26.8%
Puyallup South Hill              1.5%        45.9%        29.5%     1.7% 21.4%
Redmond Downtown                 2.6%        44.0%        24.1%     2.0% 27.3%
Redmond-Overlake                 2.4%        41.9%        29.6%     2.3% 23.7%
Renton                           2.5%        46.0%        25.5%     3.5% 22.6%
SeaTac                           2.1%        40.6%        33.8%     6.7% 16.9%
Seattle Downtown                 3.3%        13.1%         6.9%     6.9% 69.9%
Seattle First Hill/Capitol Hill  3.8%        19.4%         8.9%     9.1% 58.8%
Seattle Northgate                2.4%        41.9%        22.8%    10.3% 22.6%
Seattle South Lake Union         3.9%        21.7%         9.2%     5.5% 59.7%
Seattle University District      4.9%        31.2%        12.8%    16.2% 34.9%
Seattle Uptown                   4.2%        29.5%        12.1%     6.2% 48.0%
Silverdale                       1.5%        45.9%        21.7%     1.0% 29.9%
Tacoma Downtown                  2.6%        36.0%        19.2%     3.2% 39.0%
Tacoma Mall                      3.1%        38.4%        28.5%     2.4% 27.7%
Tukwila                          2.1%        52.7%        19.1%     3.5% 22.6%
University Place                 1.9%        47.8%        30.4%     1.2% 18.7%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [15]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [16]:
df_non_work

Mode                             Bike  Drove Alone  Shared Ride  Transit  Walk
hh_rgc
All RGCs                         3.1%        27.0%        18.4%     6.7% 44.9%
Auburn                           2.5%        34.9%        32.3%     3.3% 26.9%
Bellevue                         2.6%        28.6%        18.6%     4.2% 46.0%
Bothell Canyon Park              1.4%        46.3%        36.9%     0.2% 15.1%
Bremerton                        2.6%        31.8%        23.9%     2.1% 39.6%
Burien                           1.9%        39.5%        28.8%     3.4% 26.4%
Everett                          1.9%        34.5%        22.1%     2.3% 39.1%
Federal Way                      2.4%        32.8%        38.0%     1.9% 24.8%
Greater Downtown Kirkland        1.7%        42.3%        28.8%     4.2% 23.0%
Kent                             1.8%        33.0%        33.1%     4.2% 27.8%
Kirkland Totem Lake              1.8%        46.2%        32.5%     1.8% 17.8%
Lakewood                         2.6%        36.9%        33.1%     0.8% 26.6%
Lynnwood                         1.9%        39.7%        34.4%     2.4% 21.7%
Not in RGC                       1.4%        42.3%        40.9%     1.9% 13.5%
Puyallup Downtown                1.5%        37.2%        30.5%     1.8% 28.9%
Puyallup South Hill              1.6%        41.3%        32.2%     1.4% 23.5%
Redmond Downtown                 2.5%        39.0%        26.5%     2.2% 29.8%
Redmond-Overlake                 2.4%        37.1%        32.5%     2.5% 25.5%
Renton                           2.4%        41.6%        28.0%     3.8% 24.2%
SeaTac                           2.1%        37.0%        36.4%     6.7% 17.8%
Seattle Downtown                 3.3%        11.5%         7.5%     7.8% 69.9%
Seattle First Hill/Capitol Hill  3.8%        16.9%         9.6%     9.8% 59.8%
Seattle Northgate                2.3%        37.8%        25.0%    10.2% 24.7%
Seattle South Lake Union         3.8%        19.4%        10.1%     6.2% 60.5%
Seattle University District      5.0%        26.6%        13.4%    16.8% 38.2%
Seattle Uptown                   4.0%        26.1%        13.4%     6.8% 49.7%
Silverdale                       1.4%        42.0%        23.4%     0.8% 32.3%
Tacoma Downtown                  2.6%        32.4%        20.7%     3.3% 41.1%
Tacoma Mall                      3.0%        34.5%        30.4%     2.3% 29.8%
Tukwila                          1.9%        47.3%        20.9%     3.6% 26.3%
University Place                 1.9%        43.5%        33.1%     1.2% 20.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [17]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [18]:
df_work

Mode                             Bike  Drove Alone  Shared Ride  Transit  Walk
hh_rgc
All RGCs                         3.4%        44.8%         8.3%     4.4% 39.2%
Auburn                           3.2%        64.0%        14.0%     7.1% 11.7%
Bellevue                         3.4%        50.9%         8.6%     1.8% 35.3%
Bothell Canyon Park              1.5%        74.6%        17.9%     1.2%  4.7%
Bremerton                        3.7%        59.7%        11.3%     7.4% 17.8%
Burien                           2.1%        72.3%        16.3%     2.0%  7.3%
Everett                          2.6%        66.1%        10.8%     1.0% 19.4%
Federal Way                      3.6%        68.5%        15.9%     0.8% 11.2%
Greater Downtown Kirkland        1.8%        72.0%        11.9%     4.2% 10.1%
Kent                             2.6%        66.1%        14.0%     5.3% 12.1%
Kirkland Totem Lake              1.8%        77.2%        12.6%     1.1%  7.3%
Lakewood                         2.9%        71.1%        13.6%     1.1% 11.4%
Lynnwood                         2.4%        68.4%        15.9%     1.3% 12.0%
Not in RGC                       1.2%        74.6%        16.0%     2.1%  6.1%
Puyallup Downtown                1.0%        71.5%        12.9%     2.9% 11.7%
Puyallup South Hill              1.3%        72.8%        13.4%     3.4%  9.1%
Redmond Downtown                 3.4%        68.7%        12.3%     1.1% 14.5%
Redmond-Overlake                 2.6%        67.8%        14.4%     1.1% 14.1%
Renton                           2.9%        71.6%        11.2%     1.4% 13.0%
SeaTac                           2.1%        65.0%        16.0%     6.1% 10.8%
Seattle Downtown                 3.3%        19.7%         4.2%     3.0% 69.7%
Seattle First Hill/Capitol Hill  3.9%        29.8%         5.6%     5.9% 54.6%
Seattle Northgate                2.8%        63.5%        11.3%    10.9% 11.6%
Seattle South Lake Union         4.1%        31.0%         5.4%     2.8% 56.6%
Seattle University District      4.3%        55.2%         9.4%    13.2% 17.8%
Seattle Uptown                   4.9%        44.0%         6.6%     3.6% 40.8%
Silverdale                       2.0%        67.6%        11.9%     1.8% 16.7%
Tacoma Downtown                  2.7%        59.2%         9.7%     2.7% 25.7%
Tacoma Mall                      4.3%        65.7%        14.4%     3.3% 12.2%
Tukwila                          3.1%        74.7%        11.6%     2.9%  7.7%
University Place                 2.0%        76.4%        12.6%     1.1%  7.9%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [19]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Regional Geography

:::{.panel-tabset}

#### All Purposes

In [20]:
df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_rg, 'hh_rg_proposed')

df_all

Mode,Bike,Drove Alone,Shared Ride,Transit,Walk
hh_rg_proposed,,,,,
Cities and Towns,1.2%,46.0%,40.1%,0.6%,12.0%
Core Cities,1.4%,46.6%,37.8%,1.9%,12.3%
High Capacity Transit Communities,1.3%,47.0%,38.7%,1.4%,11.6%
Metropolitan Cities,2.1%,40.9%,29.0%,4.3%,23.6%
Rural Areas,0.9%,50.7%,41.8%,0.4%,6.2%
Urban Unincorporated Areas,1.2%,46.0%,42.8%,0.5%,9.5%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [21]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [22]:
df_non_work

Mode,Bike,Drove Alone,Shared Ride,Transit,Walk
hh_rg_proposed,,,,,
Cities and Towns,1.3%,41.6%,43.5%,0.6%,13.1%
Core Cities,1.5%,42.2%,41.1%,1.9%,13.3%
High Capacity Transit Communities,1.4%,42.8%,42.0%,1.4%,12.5%
Metropolitan Cities,2.1%,36.9%,31.8%,4.5%,24.8%
Rural Areas,1.0%,47.0%,45.2%,0.3%,6.5%
Urban Unincorporated Areas,1.3%,41.7%,46.3%,0.4%,10.2%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [23]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [24]:
df_work

Mode,Bike,Drove Alone,Shared Ride,Transit,Walk
hh_rg_proposed,,,,,
Cities and Towns,0.6%,76.4%,17.3%,0.8%,4.8%
Core Cities,1.2%,74.7%,16.3%,2.0%,5.8%
High Capacity Transit Communities,1.0%,75.7%,16.4%,1.8%,5.1%
Metropolitan Cities,2.3%,64.2%,13.1%,3.6%,16.7%
Rural Areas,0.5%,78.4%,16.2%,1.1%,3.8%
Urban Unincorporated Areas,0.7%,77.6%,17.2%,0.9%,3.7%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [25]:
trip_work.style.format("{:0,.0f}")

:::

:::

In [26]:
equity_geogs = util.summary_config['hh_equity_geogs']

trip_equity_geog = pd.DataFrame()
df_all = pd.DataFrame()
df_work = pd.DataFrame()
df_non_work = pd.DataFrame()
trip_work = pd.DataFrame()
trip_non_work = pd.DataFrame()

for geog in equity_geogs:
    df = prep_trip_df(pd.read_csv(util.output_path/ ('agg/dash/mode_share_'+geog+'.csv')))
    df['equity_geog'] = df[geog].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'})
    df['EFA'] = geog
    # trip_equity_geog = pd.concat([trip_equity_geog, df[['equity_geog_type', 'dpurp', 'Mode', 'equity_geog','trexpfac', 'Trip Type']]])

    _df_all, _df_work, _df_non_work, _trip_all, _trip_work, _trip_non_work = calc_mode_share(df, 'equity_geog')

    _df_all['EFA'] = geog
    _df_work['EFA'] = geog
    _df_non_work['EFA'] = geog
    _trip_all['EFA'] = geog
    _trip_work['EFA'] = geog
    _trip_non_work['EFA'] = geog


    df_all = pd.concat([df_all, _df_all])
    df_work = pd.concat([df_work, _df_work])
    df_non_work = pd.concat([df_non_work, _df_non_work])
    trip_all = pd.concat([trip_all, _trip_all])
    trip_work = pd.concat([trip_work, _trip_work])
    trip_non_work = pd.concat([trip_non_work, _trip_non_work])

col_dict = {'hh_efa_dis': 'Disability',
                                'hh_efa_pov200': 'Income',
                                'hh_efa_poc': 'People of Color',
                                'hh_efa_lep': 'LEP',
                                'hh_efa_older': 'Older Adult',
                                'hh_efa_youth': 'Youth'}
col_list = ['EFA','Drove Alone', 'Shared Ride', 'Transit','Walk', 'Bike']

df_all['EFA'] = df_all['EFA'].map(col_dict)
df_all = df_all[col_list]
df_work['EFA'] = df_work['EFA'].map(col_dict)
df_work = df_work[col_list]
df_non_work['EFA'] = df_non_work['EFA'].map(col_dict)
df_non_work = df_non_work[col_list]
trip_all['EFA'] = trip_all['EFA'].map(col_dict)
trip_all = trip_all[col_list]
trip_work['EFA'] = trip_work['EFA'].map(col_dict)
trip_work = trip_work[col_list]
trip_non_work['EFA'] = trip_non_work['EFA'].map(col_dict)
trip_non_work = trip_non_work[col_list]

### Equity Focus Areas

:::{.panel-tabset}

#### All Purposes

In [27]:
df_all

Mode,EFA,Drove Alone,Shared Ride,Transit,Walk,Bike
equity_geog,,,,,,
Above Regional Average,Disability,45.4%,36.1%,2.1%,14.9%,1.5%
Below Regional Average,Disability,45.8%,36.6%,2.2%,13.8%,1.5%
Higher Share of Equity Population,Disability,43.6%,34.5%,2.2%,18.1%,1.6%
Above Regional Average,Older Adult,46.3%,36.8%,1.9%,13.6%,1.4%
Below Regional Average,Older Adult,44.4%,35.9%,2.3%,15.7%,1.7%
Higher Share of Equity Population,Older Adult,47.1%,35.6%,2.3%,13.8%,1.3%
Above Regional Average,LEP,45.6%,36.9%,2.0%,13.9%,1.5%
Below Regional Average,LEP,45.5%,35.5%,2.1%,15.3%,1.5%
Higher Share of Equity Population,LEP,44.6%,37.6%,2.6%,13.6%,1.6%
Above Regional Average,Income,44.7%,35.7%,2.3%,15.7%,1.6%
Below Regional Average,Income,46.5%,36.5%,1.9%,13.6%,1.4%
Higher Share of Equity Population,Income,41.7%,35.4%,3.2%,17.8%,1.9%
Above Regional Average,People of Color,44.1%,35.8%,2.3%,16.2%,1.6%
Below Regional Average,People of Color,46.8%,36.1%,1.9%,13.8%,1.4%
Higher Share of Equity Population,People of Color,43.1%,37.0%,2.9%,15.3%,1.7%
Above Regional Average,Youth,46.8%,39.2%,1.4%,11.2%,1.3%
Below Regional Average,Youth,44.4%,32.3%,3.1%,18.4%,1.8%
Higher Share of Equity Population,Youth,45.0%,42.6%,1.0%,10.1%,1.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

:::

#### Non-Work Purposes

In [28]:
df_non_work

Mode,EFA,Drove Alone,Shared Ride,Transit,Walk,Bike
equity_geog,,,,,,
Above Regional Average,Disability,41.4%,39.2%,2.1%,15.8%,1.5%
Below Regional Average,Disability,41.5%,40.1%,2.2%,14.7%,1.5%
Higher Share of Equity Population,Disability,39.9%,37.3%,2.2%,19.0%,1.6%
Above Regional Average,Older Adult,42.3%,40.0%,1.9%,14.4%,1.4%
Below Regional Average,Older Adult,40.0%,39.3%,2.3%,16.7%,1.7%
Higher Share of Equity Population,Older Adult,43.5%,38.3%,2.1%,14.7%,1.3%
Above Regional Average,LEP,41.4%,40.2%,2.1%,14.7%,1.5%
Below Regional Average,LEP,41.5%,38.7%,2.1%,16.2%,1.5%
Higher Share of Equity Population,LEP,40.2%,40.8%,2.7%,14.7%,1.6%
Above Regional Average,Income,40.6%,38.8%,2.3%,16.7%,1.6%
Below Regional Average,Income,42.3%,39.9%,1.9%,14.4%,1.4%
Higher Share of Equity Population,Income,37.7%,38.3%,3.2%,19.0%,1.9%
Above Regional Average,People of Color,40.0%,39.1%,2.3%,17.0%,1.7%
Below Regional Average,People of Color,42.7%,39.3%,1.8%,14.8%,1.4%
Higher Share of Equity Population,People of Color,38.9%,40.3%,3.0%,16.1%,1.7%
Above Regional Average,Youth,42.6%,42.5%,1.4%,12.1%,1.3%
Below Regional Average,Youth,40.5%,35.3%,3.1%,19.4%,1.7%
Higher Share of Equity Population,Youth,40.6%,46.1%,0.9%,11.0%,1.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

:::

#### Work

In [29]:
df_work

Mode,EFA,Drove Alone,Shared Ride,Transit,Walk,Bike
equity_geog,,,,,,
Above Regional Average,Disability,72.1%,15.6%,2.2%,8.8%,1.4%
Below Regional Average,Disability,72.4%,15.4%,2.3%,8.5%,1.4%
Higher Share of Equity Population,Disability,70.0%,14.8%,2.3%,11.4%,1.5%
Above Regional Average,Older Adult,73.0%,15.6%,2.0%,8.2%,1.2%
Below Regional Average,Older Adult,71.1%,15.3%,2.3%,9.7%,1.6%
Higher Share of Equity Population,Older Adult,73.2%,15.1%,3.1%,7.6%,1.1%
Above Regional Average,LEP,72.2%,15.7%,1.8%,9.0%,1.3%
Below Regional Average,LEP,71.7%,14.9%,2.5%,9.5%,1.4%
Higher Share of Equity Population,LEP,72.9%,16.6%,2.1%,7.0%,1.5%
Above Regional Average,Income,70.9%,15.5%,2.4%,9.7%,1.5%
Below Regional Average,Income,72.8%,15.3%,2.1%,8.5%,1.3%
Higher Share of Equity Population,Income,70.0%,15.5%,2.9%,9.9%,1.8%
Above Regional Average,People of Color,70.1%,15.2%,2.0%,11.0%,1.6%
Below Regional Average,People of Color,73.7%,15.3%,2.4%,7.4%,1.2%
Higher Share of Equity Population,People of Color,70.0%,15.9%,2.3%,10.1%,1.6%
Above Regional Average,Youth,75.7%,16.5%,1.6%,5.3%,1.0%
Below Regional Average,Youth,68.7%,14.1%,3.0%,12.4%,1.8%
Higher Share of Equity Population,Youth,76.2%,17.5%,1.2%,4.4%,0.8%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

:::

:::

:::

## Mode Share by Trip Destination

In [30]:
tour_rgc_dest = pd.read_csv(util.output_path / 'agg/dash/tour_rgc_dest.csv')
trip_rgc_dest = pd.read_csv(util.output_path / 'agg/dash/trip_rgc_dest.csv')

# order RGCs

# all individual centers
l = tour_rgc_dest['tour_d_rgc'].sort_values().unique().tolist()
l.remove('Not in RGC')
l.remove(np.nan)

# aggregated centers
geog_order = ["Region","In RGC","Not in RGC"]

# combine
geog_order.extend(l)

In [31]:
def get_rgc_location(df, dest_col):
    # regional data
    df_region = df.copy()
    df_region[dest_col] = "Region"

    # aggregated centers
    df_isrgc = df.copy()
    df_isrgc.loc[df_isrgc[dest_col]!="Not in RGC", dest_col] = "In RGC"


    df_rgc = pd.concat([
        df_region,
        df_isrgc,
    # 2025 notes:
    # 7 records in the data are missing both mode and and RGC values
    # remove these records
        df.loc[~df[dest_col].isna()]
        ])

    df_rgc[dest_col] = pd.Categorical(df_rgc[dest_col], ordered=True,
                    categories=geog_order)
    
    return df_rgc

df_tour = get_rgc_location(tour_rgc_dest, 'tour_d_rgc')
df_trip = get_rgc_location(trip_rgc_dest, 'trip_d_rgc')

:::{.panel-tabset}

### Regional Growth Center

In [32]:
def calc_mode_share_by_rgc(df_trip_geog, geog_col, mode_col, n_trip_col):

    df = df_trip_geog.pivot_table(columns=mode_col, index=geog_col, values=n_trip_col, aggfunc='sum', observed=True)

    df = df.apply(lambda x: x/ df_trip_geog.groupby(geog_col, observed=True)[n_trip_col].sum())

    return df

:::{.panel-tabset}

### All Trips

\[TRIP\] Mode Share for All Purposes by Regional Center (Destination Location)

In [33]:
calc_mode_share_by_rgc(df_trip, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.5%,21.4%,14.1%,44.5%,1.6%,0.3%,2.2%,14.5%
In RGC,1.9%,16.0%,9.0%,42.4%,0.5%,0.8%,5.3%,24.2%
Not in RGC,1.4%,22.4%,15.1%,44.9%,1.8%,0.2%,1.5%,12.5%
Auburn,1.1%,22.3%,12.5%,48.1%,0.6%,0.3%,2.8%,12.3%
Bellevue,1.7%,15.2%,8.8%,43.0%,0.4%,0.5%,2.6%,27.8%
Bothell Canyon Park,1.0%,22.0%,14.6%,53.8%,1.1%,0.2%,0.4%,6.9%
Bremerton,1.6%,15.7%,8.9%,53.9%,0.1%,0.3%,2.0%,17.7%
Burien,1.2%,22.8%,12.6%,45.9%,0.8%,0.2%,2.3%,14.2%
Everett,1.2%,18.8%,11.1%,47.5%,0.6%,0.3%,1.6%,18.8%
Federal Way,0.9%,24.4%,13.3%,48.3%,0.5%,0.2%,2.0%,10.4%
Greater Downtown Kirkland,1.2%,19.8%,11.4%,49.7%,0.8%,0.3%,2.3%,14.6%
Issaquah,0.9%,21.7%,12.4%,56.6%,0.5%,0.2%,0.6%,7.1%
Kent,1.0%,22.4%,13.8%,47.7%,0.9%,0.2%,2.9%,11.1%
Kirkland Totem Lake,1.2%,20.5%,11.6%,54.4%,0.6%,0.3%,1.2%,10.2%
Lakewood,1.0%,25.5%,13.2%,48.1%,0.3%,0.4%,0.7%,10.8%
Lynnwood,1.0%,22.5%,12.4%,51.9%,0.6%,0.3%,1.1%,10.2%
Puyallup Downtown,1.0%,23.8%,14.3%,46.8%,1.2%,0.3%,1.1%,11.4%
Puyallup South Hill,1.0%,23.2%,12.7%,52.1%,0.5%,0.2%,0.4%,9.9%
Redmond Downtown,1.4%,21.2%,13.0%,45.2%,1.1%,0.2%,1.3%,16.4%
Redmond-Overlake,1.3%,16.6%,10.0%,57.9%,0.4%,0.3%,1.2%,12.3%
Renton,1.3%,20.6%,11.4%,52.5%,0.8%,0.3%,1.7%,11.4%
SeaTac,1.5%,18.6%,11.8%,50.6%,0.8%,0.2%,4.1%,12.4%
Seattle Downtown,2.3%,9.3%,5.1%,28.9%,0.2%,1.7%,11.8%,40.7%
Seattle First Hill/Capitol Hill,2.9%,10.3%,5.3%,27.7%,0.3%,1.7%,8.5%,43.3%
Seattle Northgate,1.6%,18.0%,8.4%,45.8%,0.6%,0.4%,10.0%,15.3%
Seattle South Lake Union,2.7%,10.6%,5.1%,37.2%,0.1%,1.3%,6.3%,36.7%
Seattle University District,3.3%,12.9%,7.2%,39.4%,0.4%,0.5%,12.2%,24.2%
Seattle Uptown,3.1%,12.0%,5.7%,35.1%,0.2%,0.9%,4.9%,38.2%
Silverdale,0.9%,24.1%,13.1%,50.9%,0.7%,0.2%,0.2%,10.0%
Tacoma Downtown,1.7%,15.5%,8.9%,48.4%,0.5%,0.4%,2.7%,21.9%
Tacoma Mall,1.7%,21.5%,11.5%,47.8%,0.7%,0.5%,1.4%,14.9%
Tukwila,0.9%,22.5%,12.2%,55.3%,0.1%,0.2%,2.5%,6.2%
University Place,1.4%,21.9%,12.0%,47.5%,1.2%,0.3%,0.8%,14.9%

\[TRIP\] Mode Share to Work by Regional Center (Destination Location)

### Work

In [34]:
df_trip_work = df_trip[df_trip['dpurp'] == 'Work'].copy()
calc_mode_share_by_rgc(df_trip_work, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.4%,9.4%,5.9%,71.6%,0.0%,0.6%,2.3%,8.9%
In RGC,1.7%,8.6%,5.4%,62.4%,0.0%,1.0%,4.7%,16.1%
Not in RGC,1.2%,9.9%,6.1%,76.6%,0.0%,0.3%,0.9%,5.0%
Auburn,1.0%,10.0%,6.5%,73.9%,NaN,0.3%,1.2%,7.1%
Bellevue,1.5%,9.0%,6.2%,65.4%,NaN,0.6%,1.7%,15.6%
Bothell Canyon Park,1.0%,9.8%,6.3%,78.8%,NaN,0.3%,0.2%,3.6%
Bremerton,1.2%,10.0%,6.2%,74.0%,NaN,0.3%,2.0%,6.4%
Burien,1.5%,10.0%,6.2%,73.6%,NaN,0.3%,1.1%,7.3%
Everett,1.2%,9.1%,5.6%,72.7%,0.0%,0.3%,0.5%,10.6%
Federal Way,1.1%,9.8%,6.3%,76.2%,0.0%,0.2%,0.6%,5.9%
Greater Downtown Kirkland,1.3%,9.8%,5.9%,75.9%,0.0%,0.4%,1.0%,5.7%
Issaquah,0.6%,9.8%,6.2%,77.9%,NaN,0.3%,0.5%,4.7%
Kent,1.2%,9.8%,6.7%,73.6%,0.0%,0.4%,1.6%,6.9%
Kirkland Totem Lake,1.1%,9.6%,5.8%,77.0%,NaN,0.3%,0.6%,5.5%
Lakewood,1.5%,8.6%,5.5%,75.4%,NaN,0.2%,0.7%,8.1%
Lynnwood,1.2%,9.3%,6.0%,76.4%,NaN,0.4%,0.4%,6.3%
Puyallup Downtown,0.8%,10.4%,6.3%,73.9%,NaN,0.2%,0.9%,7.5%
Puyallup South Hill,0.9%,9.6%,5.9%,76.7%,NaN,0.1%,0.4%,6.5%
Redmond Downtown,1.4%,8.9%,5.6%,73.3%,0.0%,0.2%,0.5%,10.1%
Redmond-Overlake,1.0%,9.1%,5.9%,77.0%,NaN,0.4%,0.9%,5.6%
Renton,1.2%,9.7%,6.0%,75.4%,NaN,0.4%,0.9%,6.3%
SeaTac,1.2%,10.1%,6.4%,73.5%,NaN,0.3%,2.4%,6.1%
Seattle Downtown,2.2%,7.2%,4.5%,44.9%,NaN,1.9%,11.6%,27.8%
Seattle First Hill/Capitol Hill,2.2%,7.9%,4.8%,50.8%,0.0%,1.6%,5.7%,27.0%
Seattle Northgate,1.9%,9.2%,5.3%,73.1%,NaN,0.5%,2.0%,8.0%
Seattle South Lake Union,2.6%,7.9%,4.8%,56.9%,NaN,1.4%,3.9%,22.5%
Seattle University District,2.1%,9.5%,6.1%,67.5%,NaN,0.7%,5.3%,8.8%
Seattle Uptown,2.5%,8.2%,4.9%,57.7%,NaN,1.0%,2.6%,23.0%
Silverdale,1.2%,9.3%,5.1%,75.0%,NaN,0.2%,0.4%,8.9%
Tacoma Downtown,1.6%,9.4%,5.9%,69.9%,NaN,0.3%,1.4%,11.6%
Tacoma Mall,1.7%,9.6%,6.0%,74.6%,NaN,0.4%,0.8%,6.9%
Tukwila,1.0%,10.0%,6.2%,76.8%,NaN,0.4%,1.2%,4.4%
University Place,1.4%,10.1%,5.8%,74.2%,NaN,0.2%,0.5%,7.7%

### Non-Work

\[TRIP\] Mode Share for Non-work Purposes by Regional Center (Destination Location)

In [35]:
df_trip_non_work = df_trip[df_trip['dpurp'] != 'Work'].copy()
calc_mode_share_by_rgc(df_trip_non_work, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.5%,23.2%,15.4%,40.4%,1.8%,0.3%,2.1%,15.3%
In RGC,1.9%,18.9%,10.4%,34.7%,0.6%,0.7%,5.5%,27.3%
Not in RGC,1.5%,23.9%,16.2%,41.3%,2.0%,0.2%,1.6%,13.4%
Auburn,1.1%,24.6%,13.7%,43.2%,0.7%,0.2%,3.1%,13.3%
Bellevue,1.8%,18.2%,10.1%,32.0%,0.6%,0.4%,3.0%,33.8%
Bothell Canyon Park,1.0%,27.0%,18.0%,43.6%,1.5%,0.2%,0.5%,8.2%
Bremerton,1.9%,20.9%,11.3%,35.3%,0.2%,0.3%,1.9%,28.1%
Burien,1.2%,24.3%,13.3%,42.8%,0.9%,0.2%,2.4%,15.0%
Everett,1.2%,21.6%,12.7%,40.4%,0.8%,0.3%,1.9%,21.1%
Federal Way,0.9%,26.9%,14.5%,43.6%,0.6%,0.2%,2.2%,11.1%
Greater Downtown Kirkland,1.2%,22.1%,12.7%,43.4%,1.0%,0.3%,2.6%,16.7%
Issaquah,1.0%,25.8%,14.5%,49.4%,0.6%,0.2%,0.6%,8.0%
Kent,1.0%,24.9%,15.2%,42.5%,1.0%,0.2%,3.2%,11.9%
Kirkland Totem Lake,1.2%,23.1%,13.0%,49.0%,0.8%,0.2%,1.4%,11.3%
Lakewood,0.9%,28.7%,14.7%,42.9%,0.3%,0.4%,0.7%,11.3%
Lynnwood,1.0%,25.6%,13.9%,46.1%,0.7%,0.3%,1.2%,11.1%
Puyallup Downtown,1.0%,26.2%,15.7%,42.0%,1.4%,0.3%,1.2%,12.1%
Puyallup South Hill,1.0%,25.8%,14.0%,47.5%,0.5%,0.3%,0.4%,10.6%
Redmond Downtown,1.4%,23.4%,14.4%,40.2%,1.3%,0.2%,1.4%,17.5%
Redmond-Overlake,1.5%,22.4%,13.1%,43.1%,0.7%,0.2%,1.5%,17.5%
Renton,1.3%,24.5%,13.4%,44.1%,1.1%,0.3%,2.0%,13.2%
SeaTac,1.6%,23.0%,14.5%,38.9%,1.3%,0.2%,4.9%,15.6%
Seattle Downtown,2.4%,10.8%,5.5%,17.6%,0.3%,1.6%,12.0%,49.9%
Seattle First Hill/Capitol Hill,3.1%,11.0%,5.4%,21.5%,0.4%,1.7%,9.2%,47.7%
Seattle Northgate,1.5%,19.9%,9.1%,39.7%,0.7%,0.3%,11.8%,16.9%
Seattle South Lake Union,2.8%,12.1%,5.3%,26.0%,0.2%,1.3%,7.6%,44.7%
Seattle University District,3.6%,13.9%,7.5%,31.1%,0.5%,0.4%,14.2%,28.7%
Seattle Uptown,3.3%,13.1%,6.0%,28.5%,0.2%,0.9%,5.5%,42.6%
Silverdale,0.8%,26.9%,14.6%,46.3%,0.8%,0.2%,0.1%,10.2%
Tacoma Downtown,1.8%,18.5%,10.3%,37.7%,0.8%,0.5%,3.4%,27.1%
Tacoma Mall,1.6%,24.5%,12.9%,41.0%,0.9%,0.5%,1.5%,17.0%
Tukwila,0.9%,26.9%,14.4%,47.6%,0.1%,0.2%,3.0%,6.9%
University Place,1.4%,23.5%,12.9%,44.0%,1.3%,0.4%,0.8%,15.8%

:::

:::

## Mode Share by Tour Destination

:::{.panel-tabset}

### RGC

:::{.panel-tabset}

### All Tours

\[TOUR\] Mode Share for All Purposes by Regional Center (Destination Location)

In [36]:
calc_mode_share_by_rgc(df_tour, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,Park,SOV,School Bus,TNC,Transit,Walk
tour_d_rgc,,,,,,,,,
Region,1.3%,22.1%,19.3%,0.1%,37.9%,2.6%,0.5%,3.2%,13.0%
In RGC,1.5%,18.5%,14.3%,0.5%,39.9%,0.6%,1.0%,7.6%,16.2%
Not in RGC,1.3%,23.2%,20.8%,0.1%,37.3%,3.1%,0.3%,1.9%,12.0%
Auburn,0.7%,25.5%,19.8%,0.1%,42.6%,0.3%,0.3%,2.4%,8.4%
Bellevue,1.3%,17.8%,14.3%,0.2%,43.0%,0.4%,0.7%,3.4%,18.9%
Bothell Canyon Park,0.9%,23.9%,22.2%,0.0%,44.7%,1.9%,0.4%,0.8%,5.0%
Bremerton,1.2%,21.0%,15.4%,0.7%,49.8%,0.1%,0.4%,0.8%,10.6%
Burien,0.9%,24.3%,18.1%,0.1%,39.4%,1.5%,0.2%,4.0%,11.5%
Everett,0.9%,22.3%,18.1%,0.1%,40.8%,1.0%,0.4%,2.6%,13.8%
Federal Way,0.7%,25.7%,19.6%,0.0%,42.0%,0.5%,0.2%,2.5%,8.7%
Greater Downtown Kirkland,0.9%,22.7%,17.9%,0.0%,43.6%,1.3%,0.4%,2.5%,10.7%
Issaquah,0.8%,24.0%,18.8%,0.1%,48.9%,0.7%,0.4%,1.0%,5.5%
Kent,0.7%,25.5%,21.7%,0.1%,39.5%,1.6%,0.3%,2.8%,7.8%
Kirkland Totem Lake,0.9%,22.0%,17.1%,0.0%,48.9%,0.8%,0.3%,2.0%,7.8%
Lakewood,0.8%,26.3%,19.3%,0.0%,43.4%,0.1%,0.4%,1.2%,8.5%
Lynnwood,0.8%,24.9%,18.2%,0.0%,46.0%,0.6%,0.4%,1.8%,7.2%
Puyallup Downtown,0.7%,26.6%,22.7%,0.0%,38.7%,2.4%,0.4%,1.3%,7.2%
Puyallup South Hill,0.8%,24.7%,18.5%,0.0%,47.3%,0.2%,0.3%,0.5%,7.6%
Redmond Downtown,0.9%,24.0%,20.9%,0.0%,37.4%,2.3%,0.2%,2.1%,12.2%
Redmond-Overlake,1.1%,18.4%,14.7%,0.2%,55.2%,0.2%,0.6%,1.3%,8.2%
Renton,0.9%,22.3%,19.1%,0.1%,46.1%,1.5%,0.4%,2.3%,7.2%
SeaTac,1.0%,20.9%,16.4%,0.3%,49.0%,0.4%,0.4%,3.7%,7.8%
Seattle Downtown,2.1%,11.7%,8.7%,1.5%,30.0%,0.3%,2.3%,18.1%,25.3%
Seattle First Hill/Capitol Hill,2.3%,13.8%,10.0%,0.5%,29.2%,0.6%,1.5%,12.0%,30.2%
Seattle Northgate,1.4%,19.8%,15.3%,0.1%,42.5%,1.1%,0.5%,6.4%,13.0%
Seattle South Lake Union,2.6%,13.6%,9.6%,0.5%,37.9%,0.1%,1.6%,8.6%,25.5%
Seattle University District,2.6%,14.2%,10.8%,0.5%,37.6%,0.6%,0.6%,16.6%,16.5%
Seattle Uptown,2.3%,15.3%,10.4%,0.3%,33.4%,0.2%,1.0%,6.3%,30.9%
Silverdale,0.6%,26.8%,20.1%,0.0%,44.6%,1.1%,0.3%,0.2%,6.3%
Tacoma Downtown,1.3%,19.2%,15.5%,0.1%,45.8%,0.8%,0.5%,3.5%,13.3%
Tacoma Mall,1.1%,24.3%,17.3%,0.0%,44.7%,0.5%,0.5%,1.6%,9.9%
Tukwila,0.9%,24.7%,18.2%,0.1%,48.7%,0.0%,0.4%,3.7%,3.4%
University Place,0.9%,24.6%,17.6%,0.0%,41.7%,1.2%,0.5%,1.1%,12.4%

### Work

\[TOUR\] Mode Share to Work by Regional Center (Destination Location)

In [37]:
df_tour_work = df_tour[df_tour['pdpurp'] == 'Work'].copy()
calc_mode_share_by_rgc(df_tour_work, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,Park,SOV,TNC,Transit,Walk
tour_d_rgc,,,,,,,,
Region,1.4%,15.3%,12.5%,0.5%,62.2%,1.1%,2.7%,4.3%
In RGC,1.8%,14.0%,11.4%,1.1%,55.6%,1.8%,5.8%,8.5%
Not in RGC,1.1%,16.1%,13.1%,0.2%,66.0%,0.6%,1.0%,1.8%
Auburn,0.9%,17.3%,14.0%,0.2%,62.7%,0.5%,1.8%,2.6%
Bellevue,1.6%,15.2%,13.2%,0.4%,59.5%,1.0%,2.0%,7.2%
Bothell Canyon Park,1.0%,15.8%,13.7%,0.1%,67.8%,0.8%,0.3%,0.6%
Bremerton,1.0%,17.1%,13.2%,1.2%,64.0%,0.5%,1.2%,1.9%
Burien,1.3%,16.0%,12.3%,0.3%,65.8%,0.6%,1.3%,2.4%
Everett,1.2%,15.9%,13.2%,0.2%,63.3%,0.6%,0.6%,5.1%
Federal Way,1.2%,16.7%,13.7%,0.2%,64.5%,0.3%,1.0%,2.4%
Greater Downtown Kirkland,1.3%,15.9%,13.3%,0.1%,65.2%,0.8%,1.0%,2.5%
Issaquah,0.6%,16.5%,14.0%,0.2%,66.8%,0.6%,0.6%,0.7%
Kent,1.3%,16.5%,14.3%,0.5%,62.3%,0.8%,1.6%,2.7%
Kirkland Totem Lake,1.1%,15.9%,13.7%,0.1%,65.9%,0.6%,0.7%,1.9%
Lakewood,1.5%,14.8%,12.0%,0.1%,67.2%,0.5%,1.0%,2.9%
Lynnwood,1.3%,16.1%,12.6%,0.1%,66.1%,0.7%,0.5%,2.5%
Puyallup Downtown,0.8%,16.3%,13.9%,0.1%,64.5%,0.5%,1.5%,2.4%
Puyallup South Hill,1.0%,17.0%,13.2%,0.1%,65.7%,0.4%,0.5%,2.0%
Redmond Downtown,1.3%,15.0%,12.3%,0.2%,64.2%,0.6%,0.8%,5.6%
Redmond-Overlake,1.0%,15.5%,12.9%,0.3%,67.3%,0.8%,1.0%,1.3%
Renton,1.2%,15.7%,14.0%,0.3%,64.8%,0.7%,1.0%,2.2%
SeaTac,1.2%,17.0%,13.3%,0.5%,63.2%,0.5%,2.6%,1.7%
Seattle Downtown,2.3%,10.8%,8.7%,2.5%,42.5%,3.4%,14.2%,15.5%
Seattle First Hill/Capitol Hill,2.3%,12.7%,9.9%,1.2%,47.9%,2.7%,6.9%,16.4%
Seattle Northgate,2.2%,14.4%,11.8%,0.3%,64.0%,0.9%,2.3%,4.1%
Seattle South Lake Union,2.7%,13.3%,10.4%,1.0%,52.8%,2.4%,4.3%,13.2%
Seattle University District,1.8%,14.6%,12.0%,1.3%,61.1%,1.3%,4.8%,3.1%
Seattle Uptown,2.5%,13.4%,10.4%,0.7%,53.1%,1.6%,2.7%,15.6%
Silverdale,1.0%,16.0%,12.0%,0.2%,66.6%,0.5%,0.4%,3.3%
Tacoma Downtown,1.6%,16.3%,13.5%,0.3%,61.4%,0.6%,1.8%,4.6%
Tacoma Mall,1.6%,16.4%,13.4%,0.1%,64.5%,0.6%,1.2%,2.2%
Tukwila,1.0%,16.8%,13.9%,0.3%,65.5%,0.7%,1.4%,0.3%
University Place,1.2%,16.7%,13.1%,0.1%,64.0%,0.4%,0.7%,3.9%

### Non-Work

\[TOUR\] Mode Share for Non-work Purposes by Regional Center (Destination Location)

In [38]:
df_tour_non_work = df_tour[df_tour['pdpurp'] != 'Work'].copy()
calc_mode_share_by_rgc(df_tour_non_work, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
tour_d_rgc,,,,,,,,
Region,1.3%,24.7%,21.9%,28.6%,3.5%,0.2%,3.4%,16.3%
In RGC,1.3%,22.0%,16.5%,27.5%,1.1%,0.4%,8.9%,22.3%
Not in RGC,1.3%,25.3%,23.0%,28.8%,4.1%,0.2%,2.2%,15.0%
Auburn,0.6%,28.5%,21.9%,35.3%,0.4%,0.2%,2.6%,10.6%
Bellevue,1.0%,21.2%,15.8%,21.6%,0.8%,0.2%,5.3%,34.0%
Bothell Canyon Park,0.9%,29.2%,27.8%,29.7%,3.2%,0.2%,1.2%,7.8%
Bremerton,1.5%,27.1%,18.8%,27.6%,0.3%,0.3%,0.2%,24.2%
Burien,0.8%,25.9%,19.2%,34.3%,1.8%,0.2%,4.5%,13.3%
Everett,0.8%,25.2%,20.3%,30.8%,1.5%,0.3%,3.4%,17.7%
Federal Way,0.5%,28.1%,21.2%,35.9%,0.7%,0.2%,2.9%,10.4%
Greater Downtown Kirkland,0.7%,26.3%,20.4%,31.9%,1.9%,0.2%,3.3%,15.2%
Issaquah,0.9%,27.9%,21.2%,39.5%,1.1%,0.2%,1.2%,7.9%
Kent,0.6%,28.1%,23.9%,33.0%,2.0%,0.1%,3.1%,9.3%
Kirkland Totem Lake,0.7%,24.9%,18.8%,40.9%,1.2%,0.2%,2.7%,10.6%
Lakewood,0.6%,29.6%,21.4%,36.5%,0.1%,0.4%,1.3%,10.1%
Lynnwood,0.6%,28.0%,20.1%,39.0%,0.8%,0.2%,2.3%,8.9%
Puyallup Downtown,0.7%,29.0%,24.8%,32.6%,3.0%,0.3%,1.2%,8.4%
Puyallup South Hill,0.7%,26.9%,20.0%,42.3%,0.3%,0.3%,0.5%,9.2%
Redmond Downtown,0.7%,27.0%,23.8%,28.3%,3.1%,0.1%,2.5%,14.4%
Redmond-Overlake,1.3%,24.6%,18.8%,29.3%,0.7%,0.2%,1.9%,23.1%
Renton,0.7%,27.5%,23.1%,31.5%,2.6%,0.3%,3.3%,11.1%
SeaTac,0.8%,27.0%,21.2%,27.2%,1.1%,0.2%,5.5%,17.2%
Seattle Downtown,1.9%,12.9%,8.8%,11.8%,0.7%,0.7%,23.8%,39.4%
Seattle First Hill/Capitol Hill,2.4%,14.5%,10.1%,16.4%,0.9%,0.8%,15.4%,39.6%
Seattle Northgate,0.9%,22.7%,17.1%,30.9%,1.7%,0.2%,8.6%,17.8%
Seattle South Lake Union,2.4%,14.0%,8.7%,18.2%,0.3%,0.5%,14.3%,41.6%
Seattle University District,3.2%,13.9%,10.0%,23.1%,0.9%,0.2%,23.9%,24.8%
Seattle Uptown,2.1%,16.7%,10.4%,18.7%,0.3%,0.6%,8.9%,42.3%
Silverdale,0.5%,29.6%,22.2%,38.9%,1.3%,0.3%,0.1%,7.1%
Tacoma Downtown,1.1%,21.8%,17.3%,31.4%,1.6%,0.4%,5.1%,21.3%
Tacoma Mall,1.0%,27.8%,19.0%,36.2%,0.7%,0.4%,1.8%,13.2%
Tukwila,0.8%,28.3%,20.2%,40.8%,0.0%,0.2%,4.8%,4.9%
University Place,0.8%,27.0%,18.9%,35.3%,1.6%,0.5%,1.2%,14.9%

:::

:::