---
title: "Household"
date: today
---

In [1]:
import pandas as pd
from pathlib import Path
import util

pd.set_option('display.float_format', '{:,.0%}'.format)

In [2]:


# list of equity geographies
equity_geogs = util.summary_config['hh_equity_geogs']
# not_equity_geogs = ["NOT in " + item for item in equity_geogs]

## Household VMT

In [3]:
# vmt data
df_vmt = pd.read_csv(util.output_path / 'agg/dash/person_vmt.csv')

# add home RGC
df_vmt['is_rgc'] = 'Not in RGC'
df_vmt.loc[df_vmt['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

# Select only drivers (dorp = 1) and auto trips
df_vmt = df_vmt[df_vmt['mode'].isin(['SOV','HOV2','HOV3+']) & (df_vmt['dorp'] == 1)].copy()

df_hh = pd.read_csv(util.output_path / 'agg/dash/hh_geog.csv')
df_hh['is_rgc'] = 'Not in RGC'
df_hh.loc[df_hh['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

def vmt_per_hh(df_vmt, df_hh, geog, map=False):
    _df_vmt = df_vmt.groupby(geog).sum()[['travdist_wt']]
    df_hh = df_hh.groupby(geog).sum()[['hhexpfac']]

    df = _df_vmt.merge(df_hh, left_index=True, right_index=True)

    if map:
        df.index = df.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })
    
    
    df.loc['Region',:] = df.sum(axis=0)
    df['Average Miles per Household'] = df['travdist_wt']/df['hhexpfac']

    
    return df[['Average Miles per Household']]

:::{.panel-tabset}

### County

In [4]:
pd.set_option('display.float_format', '{:,.1f}'.format)
vmt_per_hh(df_vmt, df_hh, "hh_county")

                Average Miles per Household
hh_county
King                                   29.6
Kitsap                                 32.7
Outside Region                         75.1
Pierce                                 36.6
Snohomish                              39.5
Region                                 33.1

### Regional Growth Center

In [5]:
vmt_per_hh(df_vmt, df_hh, "is_rgc")

            Average Miles per Household
is_rgc
In RGC                              9.7
Not in RGC                         37.1
Region                             33.1

In [6]:
vmt_per_hh(df_vmt, df_hh, "hh_rgc")

                                 Average Miles per Household
hh_rgc
Auburn                                                  19.6
Bellevue                                                 6.9
Bothell Canyon Park                                     31.3
Bremerton                                                9.6
Burien                                                  22.6
Everett                                                 10.5
Federal Way                                             20.5
Greater Downtown Kirkland                               20.8
Issaquah                                                23.5
Kent                                                    14.1
Kirkland Totem Lake                                     22.3
Lakewood                                                14.8
Lynnwood                                                18.5
Not in RGC                                              37.1
Puyallup Downtown                                       19.6
Puyallup South Hill                                     23.4
Redmond Downtown                                        15.5
Redmond-Overlake                                        13.1
Renton                                                  18.9
SeaTac                                                  24.3
Seattle Downtown                                         2.0
Seattle First Hill/Capitol Hill                          3.8
Seattle Northgate                                       14.5
Seattle South Lake Union                                 3.5
Seattle University Community                             8.5
Seattle Uptown                                           6.1
Silverdale                                              11.8
Tacoma Downtown                                          8.6
Tacoma Mall                                             14.1
Tukwila                                                 23.5
University Place                                        20.4
Region                                                  33.1

### Regional Geography

In [7]:
pd.set_option('display.float_format', '{:,.1f}'.format)
vmt_per_hh(df_vmt, df_hh, "hh_rg_proposed")

                                   Average Miles per Household
hh_rg_proposed
Cities and Towns                                          48.2
Core Cities                                               32.6
High Capacity Transit Communities                         36.2
Metropolitan Cities                                       19.1
Rural Areas                                               59.8
Urban Unincorporated Areas                                45.4
Region                                                    33.1

### Equity Focus Area

In [8]:
efa_names = {
    "People of Color": "hh_efa_poc",
    "Income": "hh_efa_pov200",
    "LEP": "hh_efa_lep",
    "Disability": "hh_efa_dis",
    "Older Adults": "hh_efa_older",
    "Youth": "hh_efa_youth"
}

df = pd.DataFrame()
for name, col in efa_names.items():
    df[name] = vmt_per_hh(df_vmt, df_hh, col, map=True)
df

,People of Color,Income,LEP,Disability,Older Adults,Youth
hh_efa_poc,,,,,,
Below Regional Average,36.7,36.4,33.9,34.9,31.4,26.7
Above Regional Average,29.2,31.3,32.5,33.5,35.5,40.0
Higher Share of Equity Population,29.3,24.4,31.0,27.0,34.0,45.7
Region,33.1,33.1,33.1,33.1,33.1,33.1

:::

## Delay

:::{.panel-tabset}
### County

In [9]:
df = pd.read_csv(util.output_path / 'agg/dash/trip_time_total.csv')
df = df[(df['mode'].isin(['SOV','HOV2','HOV3+'])&(df['dorp']==1))]

In [10]:
pd.options.display.float_format = '{:0,.1f}'.format
# Hours of delay for households in these locations
# df[['Total Delay Hours']]

def delay_per_hh(geog, map=False):

    df_hh = pd.read_csv(util.output_path / 'agg/dash/hh_geog.csv')
    df_hh['is_rgc'] = 'Not in RGC'
    df_hh.loc[df_hh['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

    df = pd.read_csv(util.output_path / 'agg/dash/trip_time_total.csv')
    df['is_rgc'] = 'Not in RGC'
    df.loc[df['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'
    df = df[(df['mode'].isin(['SOV','HOV2','HOV3+'])&(df['dorp']==1))]
    df = df.groupby(geog).sum()[['travtime_wt']]

    df2 = pd.read_csv(util.output_path / 'agg/dash/trip_sov_ff_time.csv')
    df2['is_rgc'] = 'Not in RGC'
    df2.loc[df2['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'
    df2 = df2[(df2['mode'].isin(['SOV','HOV2','HOV3+'])&(df2['dorp']==1))]
    df2 = df2.groupby(geog).sum()[['sov_ff_time_wt']]
    df = df2.merge(df, on=geog)

    # Hours of delay from travel time
    df['Total Delay Hours'] = (df['travtime_wt'] - df['sov_ff_time_wt'])/60
    # Set any negative delay to 0
    df.loc[df['Total Delay Hours'] < 0, 'Total Delay Hours'] = 0

    df_hh = df_hh.groupby(geog).sum()[['hhexpfac']]
    
    
    # df.loc['Region',:] = df.sum(axis=0)
    # df['Average Miles per Household'] = df['travdist_wt']/df['hhexpfac']


    df = df.merge(df_hh, left_index=True, right_index=True)
    
    df['Average Minutes of Delay per HH'] = df['Total Delay Hours']/df['hhexpfac']*60

    if map:
        df.index = df.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

    df['Annual Hours of Delay per HH'] = df['Average Minutes of Delay per HH']*util.summary_config['weekday_to_annual']/60

    df[['Total Delay Hours',
        'Annual Hours of Delay per HH']] = df[['Total Delay Hours', 'Annual Hours of Delay per HH']].astype(int).map('{:,}'.format)


    return df[['Total Delay Hours','Average Minutes of Delay per HH','Annual Hours of Delay per HH']]

df = delay_per_hh('hh_county')
df

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
hh_county,,,
King,"109,679",6.0,31
Kitsap,"6,829",3.2,17
Outside Region,0,3.1,16
Pierce,"45,531",6.5,34
Snohomish,"54,256",8.3,44

### Regional Growth Center

In [11]:
delay_per_hh('is_rgc')

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
is_rgc,,,
In RGC,"8,750",1.8,9
Not in RGC,"207,547",7.1,37

In [12]:
delay_per_hh('hh_rgc')

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
hh_rgc,,,
Auburn,171,3.3,17
Bellevue,490,1.5,7
Bothell Canyon Park,417,9.3,49
Bremerton,70,1.3,7
Burien,358,4.3,22
Everett,250,1.2,6
Federal Way,138,3.6,19
Greater Downtown Kirkland,496,5.3,28
Issaquah,95,4.6,24
Kent,96,2.9,15
Kirkland Totem Lake,600,6.6,35
Lakewood,118,2.2,11
Lynnwood,575,5.0,26
Not in RGC,"207,547",7.1,37
Puyallup Downtown,111,3.6,19
Puyallup South Hill,217,4.9,26
Redmond Downtown,444,2.9,15
Redmond-Overlake,224,2.6,13
Renton,600,4.6,24
SeaTac,512,4.5,23
Seattle Downtown,0,0.0,0
Seattle First Hill/Capitol Hill,305,0.4,2
Seattle Northgate,392,3.6,19
Seattle South Lake Union,97,0.4,2
Seattle University Community,680,2.4,12
Seattle Uptown,128,0.7,3
Silverdale,10,0.3,1
Tacoma Downtown,503,1.0,5
Tacoma Mall,191,2.1,11
Tukwila,213,4.5,23
University Place,313,3.4,18

### Regional Geography

In [13]:
delay_per_hh('hh_rg_proposed')

,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
hh_rg_proposed,,,
Cities and Towns,"21,635",8.4,45
Core Cities,"54,547",7.0,37
High Capacity Transit Communities,"58,717",8.2,43
Metropolitan Cities,"42,174",3.6,19
Rural Areas,"28,065",7.9,42
Urban Unincorporated Areas,"11,157",9.4,50

### Equity Focus Areas

In [14]:
df = pd.DataFrame()
for name, col in efa_names.items():
    _df = delay_per_hh(col, map=True)
    _df['Group'] = name
    df = pd.concat([df, _df])

df = df.reset_index()
df.rename(columns={'index':'EFA Type'}, inplace=True)

df[['Group', 'EFA Type', 'Total Delay Hours', 'Average Minutes of Delay per HH', 'Annual Hours of Delay per HH']]

,Group,EFA Type,Total Delay Hours,Average Minutes of Delay per HH,Annual Hours of Delay per HH
0,People of Color,Below Regional Average,"116,788",6.5,34
1,People of Color,Above Regional Average,"64,144",6.3,33
2,People of Color,Higher Share of Equity Population,"35,356",6.0,31
3,Income,Below Regional Average,"139,713",7.1,37
4,Income,Above Regional Average,"51,800",5.8,31
5,Income,Higher Share of Equity Population,"24,775",4.5,24
6,LEP,Below Regional Average,"125,832",6.0,31
7,LEP,Above Regional Average,"52,321",7.2,38
8,LEP,Higher Share of Equity Population,"38,135",6.7,35
9,Disability,Below Regional Average,"128,058",7.2,38
10,Disability,Above Regional Average,"62,730",6.0,32
11,Disability,Higher Share of Equity Population,"25,500",4.4,23
12,Older Adults,Below Regional Average,"119,279",6.6,35
13,Older Adults,Above Regional Average,"71,498",6.4,34
14,Older Adults,Higher Share of Equity Population,"25,511",5.4,28
15,Youth,Below Regional Average,"99,689",5.2,27
16,Youth,Above Regional Average,"79,920",7.5,39
17,Youth,Higher Share of Equity Population,"36,679",9.0,48

:::

## Vehicle Ownership Distribution

percentage of households by number of vehicles available, by geography

In [15]:
pd.set_option('display.float_format', '{:,.0%}'.format)

hh = pd.read_csv(util.output_path / 'agg/dash/auto_ownership_efa.csv')
df_hh = hh.copy()
df_hh = df_hh[df_hh['hh_county']!="Outside Region"].copy()
# add home RGC
df_hh['is_rgc'] = 'Not in RGC'
df_hh.loc[df_hh['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 'In RGC'

equity_geogs = ['hh_efa_dis', 'hh_efa_older', 'hh_efa_lep', 'hh_efa_pov200', 'hh_efa_poc', 'hh_efa_youth']
df_hh[equity_geogs] = df_hh[equity_geogs].apply(lambda x: x.\
        map({0: 'Below Regional Average', 
             1: 'Above Regional Average', 
             2: 'Higher Share of Equity Population'}))

df_hh['hhvehs'] = df_hh['hhvehs'].map({0:"0 vehicle",
                                       1:"1 vehicle",
                                       2:"2 vehicles",
                                       3:"3 vehicles",
                                       4:"4 or more vehicles"})

In [16]:
def stat_by_geog(df, geog):
    """
    Function to calculate statistics by geography and vehicle ownership.
    """
    
    # Group by equity geography and vehicle ownership
    df_grouped = df.groupby([geog, 'hhvehs'], as_index=False)['hhexpfac'].sum()
    
    # Calculate total households in each equity geography
    total_hh = df.groupby([geog], as_index=False)['hhexpfac'].sum().rename(columns={'hhexpfac': 'total_hh'})
    
    # Merge the grouped data with total households
    df_merged = df_grouped.merge(total_hh, on=geog)
    
    # Calculate percentage of households with the specified vehicle ownership
    df_merged['percentage'] = df_merged['hhexpfac'] / df_merged['total_hh']
    
    return df_merged.pivot(index=geog, columns='hhvehs', values='percentage')

:::{.panel-tabset}

### County

In [17]:
df_region = df_hh.groupby(['hhvehs'], as_index=False)['hhexpfac'].sum()
df_region['percentage'] = df_region['hhexpfac'] / df_hh['hhexpfac'].sum()
df_region['hh_county'] = 'Region'

In [18]:
df = stat_by_geog(df_hh, 'hh_county')
pd.concat([df_region.pivot(index='hh_county', columns='hhvehs', values='percentage'),df])

hhvehs     0 vehicle  1 vehicle  2 vehicles  3 vehicles  4 or more vehicles
hh_county
Region           11%        34%         35%         14%                  7%
King             14%        36%         32%         12%                  6%
Kitsap            5%        28%         39%         18%                  9%
Pierce            8%        31%         37%         15%                  8%
Snohomish         6%        31%         38%         16%                  9%

### Regional Geography

In [19]:
df = stat_by_geog(df_hh, 'hh_rg_proposed')
df

hhvehs,0 vehicle,1 vehicle,2 vehicles,3 vehicles,4 or more vehicles
hh_rg_proposed,,,,,
Cities and Towns,3%,26%,43%,19%,10%
Core Cities,9%,36%,35%,13%,7%
High Capacity Transit Communities,6%,32%,39%,15%,8%
Metropolitan Cities,21%,41%,27%,8%,4%
Rural Areas,1%,17%,42%,26%,14%
Urban Unincorporated Areas,2%,23%,45%,19%,10%

### Regional Growth Center

In [20]:
df = stat_by_geog(df_hh, 'is_rgc')
df

hhvehs      0 vehicle  1 vehicle  2 vehicles  3 vehicles  4 or more vehicles
is_rgc
In RGC            37%        44%         14%          3%                  1%
Not in RGC         6%        32%         38%         16%                  8%

In [21]:
df = stat_by_geog(df_hh, 'hh_rgc')
df

hhvehs,0 vehicle,1 vehicle,2 vehicles,3 vehicles,4 or more vehicles
hh_rgc,,,,,
Auburn,26%,47%,19%,5%,3%
Bellevue,39%,45%,13%,2%,1%
Bothell Canyon Park,7%,45%,35%,9%,4%
Bremerton,27%,48%,18%,4%,3%
Burien,23%,48%,21%,5%,3%
Everett,32%,47%,16%,3%,2%
Federal Way,26%,46%,20%,5%,3%
Greater Downtown Kirkland,14%,52%,26%,6%,2%
Issaquah,14%,45%,32%,6%,2%
Kent,30%,45%,17%,6%,2%
Kirkland Totem Lake,14%,48%,28%,7%,3%
Lakewood,24%,49%,20%,5%,2%
Lynnwood,29%,44%,20%,4%,3%
Not in RGC,6%,32%,38%,16%,8%
Puyallup Downtown,22%,49%,21%,5%,2%
Puyallup South Hill,17%,46%,27%,7%,3%
Redmond Downtown,25%,51%,19%,4%,2%
Redmond-Overlake,29%,48%,18%,4%,1%
Renton,25%,51%,18%,4%,2%
SeaTac,16%,48%,25%,7%,4%
Seattle Downtown,54%,38%,7%,1%,0%
Seattle First Hill/Capitol Hill,47%,42%,9%,1%,0%
Seattle Northgate,30%,45%,19%,4%,2%
Seattle South Lake Union,44%,45%,10%,1%,0%
Seattle University Community,44%,40%,13%,2%,1%
Seattle Uptown,37%,47%,13%,2%,1%
Silverdale,18%,49%,25%,6%,3%
Tacoma Downtown,40%,43%,14%,2%,1%
Tacoma Mall,28%,46%,20%,4%,2%
Tukwila,17%,47%,23%,7%,5%
University Place,13%,48%,29%,6%,2%

### Equity Focus Areas

In [22]:
df = pd.DataFrame()
for name, col in efa_names.items():
    _df = stat_by_geog(df_hh,col).reset_index()
    _df['Group'] = name
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

hhvehs                                             0 vehicle  1 vehicle  \
Group           EFA Type
People of Color Above Regional Average                   14%        35%
                Below Regional Average                    8%        32%
                Higher Share of Equity Population        14%        37%
Income          Above Regional Average                   11%        36%
                Below Regional Average                    8%        31%
                Higher Share of Equity Population        18%        40%
LEP             Above Regional Average                   12%        34%
                Below Regional Average                   10%        33%
                Higher Share of Equity Population        10%        38%
Disability      Above Regional Average                   10%        35%
                Below Regional Average                    9%        32%
                Higher Share of Equity Population        16%        37%
Older Adults    Above Regional Average                    9%        32%
                Below Regional Average                   12%        35%
                Higher Share of Equity Population        10%        32%
Youth           Above Regional Average                    5%        30%
                Below Regional Average                   15%        38%
                Higher Share of Equity Population         4%        26%

hhvehs                                             2 vehicles  3 vehicles  \
Group           EFA Type
People of Color Above Regional Average                    33%         12%
                Below Regional Average                    37%         16%
                Higher Share of Equity Population         32%         11%
Income          Above Regional Average                    33%         13%
                Below Regional Average                    37%         15%
                Higher Share of Equity Population         28%          9%
LEP             Above Regional Average                    34%         13%
                Below Regional Average                    35%         14%
                Higher Share of Equity Population         33%         12%
Disability      Above Regional Average                    34%         14%
                Below Regional Average                    37%         15%
                Higher Share of Equity Population         29%         11%
Older Adults    Above Regional Average                    36%         15%
                Below Regional Average                    34%         12%
                Higher Share of Equity Population         35%         15%
Youth           Above Regional Average                    39%         17%
                Below Regional Average                    30%         11%
                Higher Share of Equity Population         42%         19%

hhvehs                                             4 or more vehicles
Group           EFA Type
People of Color Above Regional Average                             6%
                Below Regional Average                             8%
                Higher Share of Equity Population                  6%
Income          Above Regional Average                             7%
                Below Regional Average                             8%
                Higher Share of Equity Population                  5%
LEP             Above Regional Average                             7%
                Below Regional Average                             7%
                Higher Share of Equity Population                  7%
Disability      Above Regional Average                             7%
                Below Regional Average                             7%
                Higher Share of Equity Population                  6%
Older Adults    Above Regional Average                             8%
                Below Regional Average                             7%
                Higher Share of Equity Population                  7%
Youth           Above Regional Average                             9%
                Below Regional Average                             6%
                Higher Share of Equity Population                 10%

:::