In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": False, "run_validation": True, "run_network_validation": False, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "daysim-validation-notebook": ["all_tour_mode", "all_trip_mode", "auto_ownership", "day_pattern", "escort_tour_mode", "escort_trip_mode", "households", "intermediate_stop_generation", "other_home_based_tour_mode", "other_home_based_trip_mode", "persons", "school_location", "school_tour_mode", "school_trip_mode", "telecommute", "time_choice", "tours", "tour_destination", "transit_pass_ownership", "trips", "trip_destination", "workbased_subtour_generation", "workbased_subtour_mode", "work_location", "work_tour_mode", "work_trip_mode"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "R:/e2projects_two/2023_base_year/2023_survey/activitysim_format/cleaned"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to9": 5, "9to15": 9, "15to18": 15, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "network_2023_v9_time_period_fix", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/activitysim", "abm_model": "activitysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_abm": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": False, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}
run_args_dict = {"output_dir": "C:/Workspace/asim_output_6_5_26", "data_dir": "C:/Workspace/asim_data_6_5_26"}

In [2]:
# import toml

# from pathlib import Path

# config_path = Path("../../../../configuration/asim_configuration")

# input_config = toml.load(config_path/ "input_configuration.toml")

# summary_config = toml.load(config_path/ "summary_configuration.toml")

---

title: Mandatory Tour Scheduling

date: today

---

The mandatory tour scheduling model selects a tour departure and duration period (and therefore a start and end period as well) for each mandatory tour

In [3]:
import pandas as pd
import numpy as np
import plotly.express as px
import os, sys

module_path = os.path.abspath(os.path.join('../../../..')) # or the path to your source code

sys.path.insert(0, module_path)

import util
import importlib
importlib.reload(util)

In [4]:
# read data

tour = util.get_tour_data(summary_config, run_args_dict)
m_tour_data = tour.loc[tour['tour_category']=="mandatory"]
ws_tour_data = m_tour_data.loc[m_tour_data['tour_type'].isin(["work","school"])]

## tour start time

:::{.panel-tabset}



### mandatory tours

In [5]:
df_plot = m_tour_data.groupby(['source','start'])[['tour_weight']].sum().reset_index()

df_plot['percentage'] = df_plot.groupby(['source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))



fig = px.bar(df_plot, x="start", y="percentage", color="source",barmode="group",
             title="mandatory tour start time")

fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))

fig.update_layout(height=400, width=700, yaxis=dict(tickformat=".0%"), xaxis=dict(dtick="1"))

fig.show()

- number of tours with start time later than 8pm

In [6]:
df_plot.loc[df_plot['start']>=20]

    source  start  tour_weight  percentage
15   model   20.0       8759.0    0.004166
16   model   21.0       1965.0    0.000935
17   model   22.0        126.0    0.000060
18   model   23.0        217.0    0.000103
33  survey   20.0          3.0    0.001578
34  survey   21.0          2.0    0.001052

### work/school tours

In [7]:
df_plot = ws_tour_data.groupby(['source','tour_type','start'],observed=True)[['tour_weight']].sum().reset_index()

df_plot['percentage'] = df_plot.groupby(['tour_type','source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))



fig = px.bar(df_plot, x="start", y="percentage", color="source",barmode="group",
             facet_row='tour_type',
             title="work/school tour start time")

fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))

fig.update_layout(height=400, width=700, yaxis1=dict(tickformat=".0%"), yaxis2=dict(tickformat=".0%", matches=None), xaxis=dict(dtick="1"))

fig.show()

C:\Users\Modeller\AppData\Local\Temp\ipykernel_18508\1791414099.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

::: {.callout-warning}

- bars with tour counts fewer than 30

In [8]:
df_plot.loc[df_plot['tour_weight']<30]

    source tour_type  start  tour_weight  percentage
47  survey      work   14.0         18.0    0.011928
48  survey      work   15.0         14.0    0.009278
49  survey      work   16.0          9.0    0.005964
50  survey      work   17.0         10.0    0.006627
51  survey      work   18.0          2.0    0.001325
52  survey      work   20.0          3.0    0.001988
53  survey      work   21.0          2.0    0.001325
54  survey    school    5.0          1.0    0.002551
55  survey    school    6.0         19.0    0.048469
59  survey    school   10.0         10.0    0.025510
60  survey    school   11.0          6.0    0.015306
61  survey    school   12.0          4.0    0.010204
62  survey    school   13.0          6.0    0.015306
63  survey    school   14.0          4.0    0.010204
64  survey    school   15.0          2.0    0.005102
65  survey    school   16.0          4.0    0.010204
66  survey    school   17.0          5.0    0.012755

:::

- work/school tour count

In [9]:
ws_count = ws_tour_data.groupby(['source','tour_type'],observed=True)[['tour_weight']].sum().reset_index()
ws_count['trip_weight_2017_2019'] = ws_count['tour_weight'].apply(lambda x: round(x,1))

# df_plot['percentage'] = df_plot.groupby(['source'], group_keys=False)['trip_weight_2017_2019']. \

#     apply(lambda x: x / float(x.sum()))
ws_count.sort_values('tour_type', ascending=False)

   source tour_type  tour_weight  trip_weight_2017_2019
1   model    school     769261.0               769261.0
3  survey    school        392.0                  392.0
0   model      work    1333146.0              1333146.0
2  survey      work       1509.0                 1509.0

:::

## tour duration

:::{.panel-tabset}



### mandatory tours

In [10]:
m_tour_data['duration_cal'] = m_tour_data['end'] - m_tour_data['start']



df_plot = m_tour_data.groupby(['source','duration_cal'])[['tour_weight']].sum().reset_index()

df_plot['percentage'] = df_plot.groupby(['source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))

fig = px.bar(df_plot, x="duration_cal", y="percentage", color="source",barmode="group",

             title="mandatory tour duration")

fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))
fig.update_layout(height=400, width=700, yaxis=dict(tickformat=".0%"), xaxis=dict(dtick="1"))
fig.show()

C:\Users\Modeller\AppData\Local\Temp\ipykernel_18508\3159386530.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### work/school tours

In [11]:
ws_tour_data['duration_cal'] = ws_tour_data['end'] - ws_tour_data['start']



df_plot = ws_tour_data.groupby(['source','tour_type','duration_cal'],observed=True)[['tour_weight']].sum().reset_index()

df_plot['percentage'] = df_plot.groupby(['tour_type','source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))

fig = px.bar(df_plot, x="duration_cal", y="percentage", color="source",barmode="group",

             facet_row='tour_type',

             title="work/school tour duration")

fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))
fig.update_layout(height=400, width=700, font=dict(size=11), yaxis1=dict(tickformat=".0%"), yaxis2=dict(tickformat=".0%", matches=None), xaxis=dict(dtick="1"))
fig.show()

C:\Users\Modeller\AppData\Local\Temp\ipykernel_18508\3061841802.py:7: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

::: {.callout-warning}

- bars with tour counts fewer than 30

In [12]:
df_plot.loc[df_plot['tour_weight']<30]

    source tour_type  duration_cal  tour_weight  percentage
37   model    school          18.0         18.0    0.000023
38  survey      work           0.0          3.0    0.001988
39  survey      work           1.0         15.0    0.009940
53  survey      work          15.0         22.0    0.014579
54  survey      work          16.0          8.0    0.005302
55  survey      work          17.0          1.0    0.000663
56  survey    school           0.0          7.0    0.017857
57  survey    school           1.0          4.0    0.010204
58  survey    school           2.0         10.0    0.025510
59  survey    school           3.0         13.0    0.033163
60  survey    school           4.0         15.0    0.038265
61  survey    school           5.0         16.0    0.040816
62  survey    school           6.0         19.0    0.048469
66  survey    school          10.0         25.0    0.063776
67  survey    school          11.0         15.0    0.038265
68  survey    school          12.0         10.0    0.025510
69  survey    school          13.0          4.0    0.010204
70  survey    school          14.0          1.0    0.002551
71  survey    school          15.0          2.0    0.005102

:::

:::